const easyInt = [
  {
    question: "Chọn đáp án sai. Số -64 được đọc là:",
    A: "Âm sáu mươi tư",
    B: "Trừ sáu mươi tư",
    C: "Âm sáu mươi bốn",
    D: "Sáu mươi bốn",
    answer: 4,
  },
  {
    question: "Viết số sau: âm bốn trăm hai mươi ba.",
    A: "423",
    B: "-423",
    C: "234",
    D: "+ 423",
    answer: 2,
  },
  {
    question:
      "Cho các số: -8; -67; 0; 23; 58. Có bao nhiêu số nguyên âm trong các số đã cho?",
    A: "1",
    B: "2",
    C: "3",
    D: "4",
    answer: 2,
  },
  {
    question:
      "Biết nhiệt độ của thành phố Moscow trong một ngày mùa đông là -9<sup>o</sup>C. Hãy đọc nhiệt độ",
    A: "âm tám độ C",
    B: "âm mười độ C",
    C: "âm chín độ C",
    D: "chín độ C",
    answer: 3,
  },
  {
    question:
      "Nếu -30m biểu diễn độ sâu 30m dưới mực nước biển thì +20m biểu diễn độ cao là:",
    A: "-20m dưới mực nước biển",
    B: "20m dưới mực nước biển",
    C: "-20m trên mực nước biển",
    D: "20m trên mực nước biển",
    answer: 4,
  },
  {
    question:
      "Nếu 40m biểu diễn độ cao là 40m thì -25m biểu diễn độ sâu dưới mực nước biển là:",
    A: "25m dưới mực nước biển",
    B: "-25m trên mực nước biển",
    C: "25m trên mực nước biển",
    D: "-25m dưới mực nước biển",
    answer: 1,
  },
  {
    question: "Hãy đọc số nguyên âm chỉ nhiệt độ dưới 0<sup>o</sup>C sau đây: -4<sup>o</sup>C",
    A: "Bốn độ C",
    B: "Âm bốn",
    C: "Trừ bốn",
    D: "Âm bốn độ C",
    answer: 4,
  },
  {
    question: "Viết các số sau: trừ hai mươi tư, âm ba mươi sáu",
    A: "-24; 36",
    B: "-24; -36",
    C: "24; -36",
    D: "24; 36",
    answer: 2,
  },
  {
    question: "Tập hợp nào dưới đây gồm các số nguyên âm",
    A: "{-3; -2; 1}",
    B: "{-9; -2; -1}",
    C: "{-6; 1; 4}",
    D: "{1; 4; 8}",
    answer: 2,
  },
  {
    question:
      "Các số: âm ba trăm năm mươi, trừ bốn mươi sáu được viết lần lượt là",
    A: "-46; 350",
    B: "-46; -350",
    C: "-350; 46",
    D: "-350; -46",
    answer: 4,
  },
  {
    question: "Số nào sau đây không phải là số nguyên âm?",
    A: "0",
    B: "-50",
    C: "-150",
    D: "-24",
    answer: 1,
  },
  {
    question:
      "Số nào không phải là số nguyên âm trong các số: -2131, -12, 11, -11, 107, 75, -1435.",
    A: "12; 107; 75",
    B: "11; 107; 75",
    C: "-12; -11; 75",
    D: "107; 75",
    answer: 2,
  },
  {
    question: "Tập hợp các số nguyên kí hiệu là:",
    A: "N",
    B: "N*",
    C: "Z",
    D: "Z*",
    answer: 3,
  },
  {
    question: "Chọn câu đúng.",
    A: "Số 0 không phải là số nguyên",
    B: "Số 0 là số nguyên âm",
    C: "Số 0 là số nguyên dương",
    D: "Số 0 là số nguyên",
    answer: 4,
  },
  {
    question: "Chọn câu đúng?",
    A: "Z = {0; 1; 2; 3; …}",
    B: "Z = {…; -3; -2; -1; 0}",
    C: "Z = {...; -2; -1; 0; 1; 2; ...}",
    D: "Z = {...; -2; -1; 1; 2; ...}",
    answer: 3,
  },
  {
    question: "Chọn câu đúng:",
    A: "-6 ∈ N",
    B: "9 ∉ N",
    C: "-9 ∈ N",
    D: "-19 ∈ Z",
    answer: 4,
  },
  {
    question: "Số đối của -7 là:",
    A: "3",
    B: "-3",
    C: "7",
    D: "-7",
    answer: 3,
  },
  {
    question: "Khẳng định nào dưới đây là sai?",
    A: "Số tự nhiên khác 0 đều là số nguyên dương",
    B: "-3 là số nguyên âm",
    C: "Số đối của -4 là 4",
    D: "Số nguyên âm là các số nguyên khác 0",
    answer: 4,
  },
  {
    question: "Điểm gốc trong trục số là điểm nào",
    A: "Điểm 0",
    B: "Điểm 1",
    C: "Điểm 2",
    D: "Điểm -1",
    answer: 1,
  },
  {
    question: "Chiều từ trái sang phải trong trục số được gọi là:",
    A: "Chiều âm",
    B: "Chiều dương",
    C: "Chiều thuận",
    D: "Chiều nghịch",
    answer: 2,
  },
  {
    question: "Phát biểu nào sau đây đúng?",
    A: "-10 ∈ N",
    B: "-10 ∈ Z",
    C: "-10 ∉ Z",
    D: "-10 ∈ N*",
    answer: 2,
  },
  {
    question: "Chọn đáp án đúng:",
    A: "N = {…; -1; 0; 1 …}",
    B: "N* =  {0; 1; 2; 3; …}",
    C: "Z =  {…; -2; -1; 0; 1; 2; …}",
    D: "Z* = {…; -2; -1; 0; 1; 2; …}",
    answer: 3,
  },
  {
    question: "Đáp án đúng là:",
    A: "Số nguyên lớn nhất là 999 999 999",
    B: "Không có số nguyên nhỏ nhất, không có số nguyên lớn nhất",
    C: "Số nguyên nhỏ nhất là 0",
    D: "Số nguyên nhỏ nhất là -1",
    answer: 2,
  },
  {
    question: "Điểm cách -1 ba đơn vị theo chiều âm là:",
    A: "3",
    B: "-3",
    C: "-4",
    D: "4",
    answer: 3,
  },
  {
    question: "Kết luận nào sau đây là đúng?",
    A: "Số 0 vừa là số nguyên dương, vừa là số nguyên âm",
    B: "Số 1 là số nguyên dương",
    C: "Số -3 đọc là ba",
    B: "Số -25 là số nguyên dương",
    answer: 2,
  },
  {
    question:
      "Ông M đang nợ ngân hàng 200 triệu đồng. Số nào sau đây biểu diễn số tiền ông M đang có?",
    A: "-200",
    B: "200",
    C: "200 000 000",
    D: "-200 000 000",
    answer: 4,
  },
  {
    question: "Dãy nào dưới đây là các số nguyên âm?",
    A: "0, 1, 2, 3, 4, 5",
    B: "0, -1, -2, -3, -4, -5",
    C: "-2021, -2020, -2019, -2018, -1",
    D: "-21, -7, 99, -15, -16",
    answer: 3,
  },
  {
    question: "Số liền trước số nguyên -110 là",
    A: "-111",
    B: "-109",
    C: "111",
    D: "109",
    answer: 1,
  },
  {
    question: "Điểm -2021 nằm cách gốc O bao nhiêu đơn vị?",
    A: "2 019",
    B: "2 020",
    C: "2 021",
    D: "2 022",
    answer: 3,
  },
  {
    question: "Số liền sau và số liền trước của số -2 là:",
    A: "-1 và -3",
    B: "-3 và -1",
    C: "1 và 3",
    D: "3 và 1",
    answer: 1,
  },
  {
    question: "Chọn câu sai:",
    A: "-5 < -2",
    B: "0 < 4",
    C: "0 > -1",
    D: "-5 < -6",
    answer: 4,
  },
  {
    question: "Số liền trước của số -19 là số:",
    A: "20",
    B: "-17",
    C: "-18",
    D: "-20",
    answer: 4,
  },
  {
    question: "Trong các tập hợp sau, tập hợp nào là tập hợp số nguyên?",
    A: "{...; -3; -2; -1; 0; 1; 2; 3; ...}",
    B: "{-3; -2; -1; 0; 1; 2; 3}",
    C: "{...; -3; -2; -1; 0; 1; 2; 3}",
    D: "{-3; -2; -1; 0; 1; 2; 3; ...}",
    answer: 1,
  },
  {
    question: "Số đối của 13 là",
    A: "-13",
    B: "13",
    C: "31",
    D: "1/13",
    answer: 1,
  },
  {
    question: "Số đối của một số nguyên dương là",
    A: "một số nguyên âm.",
    B: "một số nguyên dương.",
    C: "số 0.",
    D: "một số nguyên lớn hơn 0.",
    answer: 1,
  },
  {
    question: "Mọi số nguyên dương đều",
    A: "lớn hơn số 0",
    B: "nhỏ hơn số 0",
    C: "lớn hơn hoặc bằng số 0",
    D: "nhỏ hơn hoặc bằng số 0",
    answer: 1,
  },
  {
    question: "Trong các phát biểu sau, phát biểu nào đúng?",
    A: "-3 < -2",
    B: "-3 > -2",
    C: "-3 > 0",
    D: "0 < -2",
    answer: 1,
  },
  {
    question: "Số nguyên âm lớn nhất là:",
    A: "-9999999",
    B: "1",
    C: "-1",
    D: "0",
    answer: 3,
  },
  {
    question: "Số nguyên dương nhỏ nhất là:",
    A: "0",
    B: "-1",
    C: "2",
    D: "1",
    answer: 4,
  },
  {
    question: "Chiều từ phải sang trái trong trục số được gọi là?",
    A: "Chiều âm",
    B: "Chiều dương",
    C: "Chiều thuận",
    D: "Chiều nghịch",
    answer: 1,
  },
  { question: " |-1|=?", A: "-1", B: "0", C: "1", D: "2", answer: 3 },
  {
    question: "Cặp số nào sau đây là hai số đối nhau:",
    A: "0 và 1",
    B: "-1 và 1",
    C: "1 và 1",
    D: "-1 và -1",
    answer: 2,
  },
  {
    question: "Điểm 5 cách điểm 1 bao nhiêu đơn vị?",
    A: "3",
    B: "5",
    C: "2",
    D: "4",
    answer: 4,
  },
  {
    question: "Điền kí hiệu tập số phù hợp vào chỗ trống  ",
    A: "N",
    B: "N*",
    C: "Z",
    D: "Không có tập số nào",
    answer: 3,
  },
  {
    question: "Tập hợp các số nguyên gồm:",
    A: "Số nguyên âm, 0 và số nguyên dương",
    B: "0 và số nguyên âm",
    C: "0 và số nguyên dương",
    D: "Số nguyên âm và số nguyên dương",
    answer: 1,
  },
  {
    question: "Khẳng định nào sai",
    A: "-15 < 0",
    B: "-2021 < 2021",
    C: "1 > -10",
    D: "-99999 > 0",
    answer: 4,
  },
  {
    question: "Số nguyên dương nhỏ nhất có 2 chữ số là:",
    A: "11",
    B: "10",
    C: "-10",
    D: "99",
    answer: 2,
  },
  {
    question:
      "Nhiệt độ các thành phố: Hà Nội 34<sup>o</sup>C, Huế 33<sup>o</sup>C, Đà Nẵng 31<sup>o</sup>C, Hồ Chí Minh 30<sup>o</sup>C. Thành phố nào có nhiệt độ thấp nhất?",
    A: "Hà Nội",
    B: "Huế",
    C: "Đà Nẵng",
    D: "Hồ Chí Minh",
    answer: 4,
  },
  {
    question: "Kết quả của phép tính 25 + 15 là:",
    A: "40",
    B: "10",
    C: "50",
    D: "30",
    answer: 1,
  },
  {
    question: "Kết quả của phép tính (-100) + (-50) là:",
    A: "-50",
    B: "50",
    C: "150",
    D: "-150",
    answer: 4,
  },
  {
    question: "Tổng của hai số -313 và -211 là:",
    A: "534",
    B: "524",
    C: "-524",
    D: "-534",
    answer: 3,
  },
  {
    question: "Tổng của -161 và -810 là:",
    A: "-971",
    B: "971",
    C: "-649",
    D: "649",
    answer: 1,
  },
  {
    question: "Kết quả của phép tính (-50) + 30 là:",
    A: "-20",
    B: "20",
    C: "-30",
    D: "80",
    answer: 1,
  },
  {
    question: "Số nguyên nào dưới dây là kết quả của phép tính 52 + (-122)?",
    A: "-70",
    B: "70",
    C: "60",
    D: "-60",
    answer: 1,
  },
  {
    question: "Tính (-909) + 909",
    A: "1818",
    B: "1",
    C: "0",
    D: "-1818",
    answer: 3,
  },
  {
    question: "Phép cộng các số nguyên có tính chất nào sau đây:",
    A: "Giao hoán",
    B: "Kết hợp",
    C: "Cộng với số 0",
    D: "Tất cả các đáp án trên",
    answer: 4,
  },
  {
    question: "Kết quả của phép tính (-89) + 0 là:",
    A: "-89",
    B: "-90",
    C: "0",
    D: "89",
    answer: 1,
  },
  {
    question: "Tính (-978) + 978",
    A: "0",
    B: "978",
    C: "1956",
    D: "980",
    answer: 1,
  },
  {
    question: "Chọn câu đúng:",
    A: "(-98) + (-89) = (-89) + (-98)",
    B: "(-98) + (-89) > (-89) + (-98)",
    C: "(-98) + (-89) < (-89) + (-98)",
    D: "(-98) + (-89) = -177",
    answer: 1,
  },
  {
    question:
      "Cho các số: -16; -7; -1; 0; 2; 7 . Hai trong các số trên có tổng bằng -5 là:",
    A: "-7 + 2",
    B: "-7 + (-1)",
    C: "-16 + 7",
    D: "-7 + 0",
    answer: 1,
  },
  {
    question: "Kết quả phép tính (-3) + 5 là ?",
    A: "8",
    B: "2",
    C: "-8",
    D: "-2",
    answer: 2,
  },
  {
    question: "Kết quả phép tính (-4) + (-6) là ?",
    A: "2",
    B: "10",
    C: "-10",
    D: "-2",
    answer: 3,
  },
  {
    question: "Kết quả phép tính 9 + (-15) là ?",
    A: "-6",
    B: "6",
    C: "-24",
    D: "24",
    answer: 1,
  },
  {
    question: "Kết quả phép tính 7 -(-2) là ?",
    A: "5",
    B: "14",
    C: "-5",
    D: "9",
    answer: 4,
  },
  {
    question: "Kết quả phép tính (-10) -(-20) là ?",
    A: "-10",
    B: "10",
    C: "-30",
    D: "-200",
    answer: 2,
  },
  {
    question: "Kết quả phép tính -(-35) + 25 là ?",
    A: "10",
    B: "5",
    C: "60",
    D: "-10",
    answer: 3,
  },
  {
    question: "Tính 125 -200",
    A: "-75",
    B: "75",
    C: "-85",
    D: "85",
    answer: 1,
  },
  {
    question: "Kết quả của phép tính (-98) + 8 + 12 + 98 là:",
    A: "0",
    B: "4",
    C: "10",
    D: "20",
    answer: 4,
  },
  {
    question: "Nếu a + c = b + c thì:",
    A: "a = b",
    B: "a < b",
    C: "a > b",
    D: "Cả A, B, C đều sai",
    answer: 1,
  },
  {
    question: "Kết quả của phép tính 898 -1 008 là:",
    A: "Số nguyên âm",
    B: "Số nguyên dương",
    C: "Số lớn hơn 3",
    D: "Số 0",
    answer: 1,
  },
  {
    question: "Tính (-551) + (-400) + (-449)",
    A: "-1 400",
    B: "-1 450",
    C: "-1 000",
    D: "-1 500",
    answer: 1,
  },
  {
    question:
      "Nhiệt độ tại Hà Nội vào buổi trưa là 32<sup>o</sup>C, vào buổi tối nhiệt độ giảm 4<sup>o</sup>C so với buổi trưa. Nhiệt độ tại Hà Nội vào buổi tối là:",
    A: "28<sup>o</sup>C",
    B: "30<sup>o</sup>C",
    C: "26<sup>o</sup>C",
    D: "31<sup>o</sup>C",
    answer: 1,
  },
  {
    question: "Thực hiện các phép tính sau: (-99) + (-11)",
    A: "-88",
    B: "-100",
    C: "-110",
    D: "-99",
    answer: 3,
  },
  {
    question: "Biểu diễn hiệu (-28) -(-32) thành dạng tổng là:",
    A: "(-28) + (-32)",
    B: "(-28) + 32",
    C: "28 + (-32)",
    D: "28 + 32",
    answer: 2,
  },
  {
    question:
      "Trên trục số, số đối của -1 999 nằm cách gốc O bao nhiêu đơn vị?",
    A: "2 000",
    B: "1 999",
    C: "1",
    D: "-1 999",
    answer: 2,
  },
  {
    question: "Thay dấu * bằng chữ số thích hợp 28 + (-(1*))  = 16",
    A: "4",
    B: "0",
    C: "9",
    D: "2",
    answer: 4,
  },
  {
    question: "Tính T = -9 + (-2) -(-3) + (-8)",
    A: "T = 4",
    B: "T = -4",
    C: "T = 16",
    D: "T = -16",
    answer: 4,
  },
  {
    question: "Kết quả của phép tính (-125) . 8 là:",
    A: "1 000",
    B: "-1 000",
    C: "-100",
    D: "-10 000",
    answer: 2,
  },
  {
    question: "Tính (-42) . (-5) được kết quả là:",
    A: "-210",
    B: "210",
    C: "-47",
    D: "37",
    answer: 2,
  },
  {
    question: "Chọn câu đúng.",
    A: "(-20) . (-5) = -100",
    B: "(-50) . (-12) = 600",
    C: "(-18) . 25 = -400",
    D: "11 . (-11) = -1 111",
    answer: 2,
  },
  {
    question: "Chọn câu trả lời đúng.",
    A: "-365 . 366 < 1",
    B: "-365 . 366 = 1",
    C: "-365 . 366 = -1",
    D: "-365 . 366 > 1",
    answer: 1,
  },
  {
    question: "Chọn câu sai.",
    A: "(-19) . (-7) > 0",
    B: "3 . (-121) < 0",
    C: "45 . (-11) < -500",
    D: "46 . (-11) < -500",
    answer: 3,
  },
  {
    question: "Tích (-3) . (-3) . (-3) . (-3) . (-3) . (-3) . (-3) bằng:",
    A: "38",
    B: "-37",
    C: "37",
    D: "(-3)8",
    answer: 2,
  },
  {
    question: "Chọn đáp án đúng.",
    A: "(-8) . (-7) < 0",
    B: "(-15) . 3 > (-2) . (-3)",
    C: "2 . 18 = (-6) . (-6)",
    D: "(-5) . 6 > 0",
    answer: 3,
  },
  {
    question:
      "Viết lại tích (-2) . (-2) . (-2) . (-3) . (-3) . (-3) dưới dạng một lũy thừa.",
    A: "2<sup>3</sup> . 3<sup>3</sup>",
    B: "-2<sup>3</sup> . 3<sup>3</sup>",
    C: "6<sup>3</sup>",
    D: "-6<sup>3</sup>",
    answer: 3,
  },
  {
    question:
      "Điền số thích hợp vào chỗ chấm: 17 . (... + 7) = 17 . (-5) + 17 . 7",
    A: "-2",
    B: "-3",
    C: "-4",
    D: "-5",
    answer: 4,
  },
  {
    question: "Chọn câu đúng.",
    A: "(-23) . (-16) > 23. (-16)",
    B: "(-23)  . (-16) = 23 . (-16)",
    C: "(-23) . (-16) < 23. (-16)",
    D: "(-23) . 16 > 23 . (-6)",
    answer: 1,
  },
  {
    question: "Tích của hai số nguyên âm là",
    A: "số nguyên âm",
    B: "số nguyên dương",
    C: "số 0",
    D: "vừa là số nguyên âm vừa là số nguyên dương",
    answer: 2,
  },
  {
    question: "Tích của hai số nguyên âm và một số nguyên dương là",
    A: "Số nguyên dương",
    B: "Số nguyên âm",
    C: "Số 0",
    D: "Số chẵn",
    answer: 1,
  },
  {
    question: "Thực hiện phép tính sau: (-5).4",
    A: "-20",
    B: "20",
    C: "10",
    D: "-10",
    answer: 1,
  },
  {
    question:
      "Cho tích 213.3 = 639. Từ đó suy ra kết quả của tích sau: (-213).3",
    A: "-639",
    B: "639",
    C: "1 278",
    D: "-1 278",
    answer: 1,
  },
  {
    question:
      "Không thực hiện phép tính, hãy so sánh: Q = (+ 999 888). (-2 022) với 0",
    A: "Q > 0",
    B: "Q < 0",
    C: "Q = 0",
    D: "Q ≤ 0",
    answer: 2,
  },
  {
    question: "Tính (-8). (-6). (-125)",
    A: "480",
    B: "-4 800",
    C: "-6 000",
    D: "-1 200",
    answer: 3,
  },
  {
    question: "Tính (-66) : (-11) ta được kết quả là:",
    A: "6",
    B: "11",
    C: "-6",
    D: "-11",
    answer: 1,
  },
  {
    question: "Tìm số nguyên x, biết: (-5) . x = 45",
    A: "x = 5",
    B: "x = 9",
    C: "x = -5",
    D: "x = -9",
    answer: 4,
  },
  {
    question: "Kết quả của phép tính (-15) : 5 là:",
    A: "3",
    B: "5",
    C: "-3",
    D: "-5",
    answer: 3,
  },
  {
    question: "Kết quả của phép tính 60 : (-6) là:",
    A: "10",
    B: "54",
    C: "-66",
    D: "-10",
    answer: 4,
  },
  {
    question: "Kết quả của phép tính 65 : (-13) là:",
    A: "-13",
    B: "13",
    C: "5",
    D: "-5",
    answer: 4,
  },
  {
    question: "Tìm giá trị của x biết: (-8).x=160",
    A: "x = -9",
    B: "x = 5",
    C: "x = -20",
    D: "x = 9",
    answer: 3,
  },
];
const mediumInt = [
  {
    question: "Chọn khẳng định đúng trong các khẳng định sau?",
    A: "Số 0 là số nguyên âm",
    B: "Số 1 là số nguyên âm",
    C: "Số -7 là số nguyên âm",
    D: "Số 0 không là số tự nhiên",
    answer: 3,
  },
  {
    question:
      "Ông Hải kinh doanh bị lỗ 700 000 000 đồng, số nguyên âm biểu thị số tiền bị lỗ của ông Hải là:",
    A: "-700 đồng",
    B: "-700 000 đồng",
    C: "-700 000 000 đồng",
    D: "700 000 000 đồng",
    answer: 3,
  },
  {
    question:
      "Nhà toán học Euclid sống vào thế kỉ 3 TCN, số nguyên âm biểu thị thế kỉ đó là:",
    A: "3",
    B: "-3",
    C: "0",
    D: "5",
    answer: 2,
  },
  {
    question: "Số phần tử của tập hợp số nguyên âm là",
    A: "5 phần tử",
    B: "10 phần tử",
    C: "100 phần tử",
    D: "vô số phần tử",
    answer: 4,
  },
  {
    question: "Dãy nào dưới đây gồm hai số nguyên âm và một số tự nhiên?",
    A: "-18, -45, 23",
    B: "36, 48, -72",
    C: "34, -45, 0",
    D: "0, 121, -60",
    answer: 1,
  },
  {
    question:
      "Độ sâu trung bình của đại dương là 3500 m dưới mực nước biển. Số nguyên âm biểu thị độ sâu đó là:",
    A: "3500 m",
    B: "-3000 m",
    C: "-3500 m",
    D: "-500 m",
    answer: 3,
  },
  {
    question:
      "Nhà nước Âu Lạc được thành lập vào khoảng năm 257 TCN. Số nguyên âm biểu thị thời gian đó là:",
    A: "257",
    B: "-257",
    C: "-275",
    D: "-725",
    answer: 2,
  },
  {
    question:
      "Nếu 50 000 đồng biểu diễn số tiền có là 50 000 đồng thì -100 000 đồng biểu diễn số tiền:",
    A: "có 100 000 đồng",
    B: "có 150 000 đồng",
    C: "nợ 100 000 đồng",
    D: "nợ 150 000 đồng",
    answer: 3,
  },
  {
    question: "Nếu 20°C biểu diễn 20 độ trên 0°C thì -5°C biểu diễn:",
    A: "-5°C trên 0°C",
    B: "-5°C dưới 0°C",
    C: "5°C trên 0°C",
    D: "5°C dưới 0°C",
    answer: 4,
  },
  {
    question:
      "Cho tập hợp A = {-5; -8; 0; 14; -70; 65; -450}. Số phần tử là số nguyên âm có trong tập hợp A là:",
    A: "7",
    B: "6",
    C: "5",
    D: "4",
    answer: 4,
  },
  {
    question: "Số nguyên âm nào sau đây lớn nhất:",
    A: "-514",
    B: "-524",
    C: "-534",
    D: "-504",
    answer: 4,
  },
  {
    question: "Số nguyên âm nào sau đây nhỏ nhất:",
    A: "-75",
    B: "-99",
    C: "-85",
    D: "-96",
    answer: 2,
  },
  {
    question: "Trên trục số, điểm cách điểm 0 ba đơn vị theo chiều âm là:",
    A: "-3",
    B: "3",
    C: "3 và -3",
    D: "0",
    answer: 1,
  },
  { question: "Số đối của 8 là:", A: "-8", B: "0", C: "8", D: "16", answer: 1 },
  {
    question: "Những điểm cách điểm 0 ba đơn vị là:",
    A: "3 và -3",
    B: "2 và -2",
    C: "2 và -3",
    D: "3 và -2",
    answer: 1,
  },
  {
    question: "Điểm -3 cách điểm 4 theo chiều dương bao nhiêu đơn vị?",
    A: "7",
    B: "2",
    C: "9",
    D: "5",
    answer: 1,
  },
  {
    question: "Nếu -2 điốp biểu diễn độ cận thị thì + 2 điốp biểu diễn …",
    A: "độ cận thị",
    B: "độ viễn thị",
    C: "độ loạn thị",
    D: "độ bình thường",
    answer: 2,
  },
  {
    question: "Điểm -4 cách điểm 4 bao nhiêu đơn vị?",
    A: "7",
    B: "8",
    C: "6",
    D: "9",
    answer: 2,
  },
  {
    question: "Những điểm cách điểm 2 ba đơn vị là?",
    A: "-1",
    B: "5",
    C: "-1 và 5",
    D: "1 và 5",
    answer: 3,
  },
  {
    question: "Trên trục số, điểm cách -1 ba đơn vị theo chiều dương là:",
    A: "-4",
    B: "2",
    C: "-4 và 2",
    D: "4",
    answer: 2,
  },
  {
    question: "Số cách số -4 bảy đơn vị theo chiều dương là:",
    A: "6",
    B: "7",
    C: "3",
    D: "5",
    answer: 3,
  },
  {
    question: "Điểm -2 cách điểm 3 bao nhiêu đơn vị?",
    A: "5",
    B: "2",
    C: "1",
    D: "8",
    answer: 1,
  },
  {
    question: "Những điểm cách điểm 3 năm đơn vị là:",
    A: "7 và -1",
    B: "6 và -2",
    C: "2 và -2",
    D: "8 và -2",
    answer: 4,
  },
  {
    question: "Tập hợp tất cả các số nguyên x thoả mãn -2 < x < 2 là:",
    A: "{-1;1;2}",
    B: "{-2;10;2}",
    C: "{-1;0;1}",
    D: "{-2;-1;0;1;2}",
    answer: 3,
  },
  {
    question: "Phát biểu nào sau đây là sai?",
    A: "-54 < -34",
    B: "-3 179 < -3279",
    C: "87 < 97",
    D: "1197 > 1 179",
    answer: 2,
  },
  {
    question: "Trong các khẳng định sau, khẳng định nào đúng?",
    A: "Số nguyên lớn hơn -1 là số nguyên dương",
    B: "Trong hai số nguyên âm, số nào có giá trị tuyệt đối nhỏ hơn thì lớn hơn",
    C: "Số nguyên nhỏ hơn 1 là số nguyên âm",
    D: "Giá trị tuyệt đối của một số nguyên là số đối của nó",
    answer: 2,
  },
  {
    question:
      "Viết tập hợp M = {x∈Z*|-4 ≤ x ≤5} dưới dạng liệt kê ta được kết quả nào sau đây?",
    A: "M = {-4; -3; -2; 1; 2; 3}",
    B: "M = {-4; -3; -2; -1; 0; 1; 3}",
    C: "M = {-2; -1; 0; 1; 2}",
    D: "M = {-4; -3; -2; -1; 1; 2; 3; 4; 5}",
    answer: 4,
  },
  {
    question:
      "Cho tập hợp M={a∈Z|-3<a≤1} . Kết quả liệt kê các phần tử của tập hợp M là:",
    A: "M = {-2; -1; 0; 1}",
    B: "M = {-2; -1; 0}",
    C: "M = {-3; -2; -1; 0; 1}",
    D: "M = {-3; -2; -1; 0}",
    answer: 1,
  },
  {
    question: "Tập hợp X gồm các số nguyên âm lớn hơn -4 là:",
    A: "X ={-3; -2; -1}",
    B: "X ={-3; -2; -1; 0}",
    C: "X ={-4; -3; -2; -1}",
    D: "X ={-5; -6; -7; ...}",
    answer: 1,
  },
  {
    question: "Tập hợp Y gồm các số nguyên dương nhỏ hơn 5 là:",
    A: "Y = {1; 2; 3; 4}",
    B: "Y = {0; 1; 2; 3; 4}",
    C: "Y = {1; 2; 3; 4; 5}",
    D: "Y = {0; 1; 2; 3; 4; 5}",
    answer: 1,
  },
  {
    question:
      "Cho các số nguyên -1; -8; 0; 4; -3. Kết quả sắp xếp theo thứ tự giảm dần là:",
    A: "-8; -3; -1; 0; 4",
    B: "4; 0; -8; -3; -1",
    C: "4; 0; -1; -3; -8",
    D: "4; -1; -3; -8; 0",
    answer: 3,
  },
  {
    question:
      "Cho các số: 8; 15; -25;  -56; 0. Sắp xếp các số theo thứ tự tăng dần ta được:",
    A: "8; 15; -25; -56; 0",
    B: "0; 8; 15; -25; -56",
    C: "-56; -25; 15; 8; 0",
    D: "-56 ; -25; 0; 8; 15",
    answer: 4,
  },
  {
    question: "Các số nguyên âm nằm giữa -5 và 3 là:",
    A: "-4; -3; -2; -1",
    B: "-1;-1; 0; 3",
    C: "-4; -3;  -2;-1; 0; 1; 2",
    D: "0; 1; 2",
    answer: 1,
  },
  {
    question: "Viết tập hợp các số nguyên x biết:. A = {x∈ Z| -5 ≤x<1}",
    A: "A = {-5; -4; -3; -2; -1; 0}",
    B: "A = {-5; -4; -3; -2; -1; 0; 1}",
    C: "A = {-4; -3; -2; -1; 0}",
    D: "A = {-4; -3; -2; -1; 0; 1}",
    answer: 1,
  },
  {
    question: "Viết tập hợp sau bằng cách khác: D = {…; -3; -2; -1; 0; 1; 2}",
    A: "D = {x∈ Z| x<2}",
    B: "D = {x∈ Z| x≤2}",
    C: "D = {x∈ Z|-3 ≤x≤2}",
    D: "D = {x∈ Z|-3<x<2}",
    answer: 2,
  },
  {
    question: "Tìm x ∈ Z, biết -10 ≤ x ≤ -7 ",
    A: "x ∈ {-10; -9; -8; -7; …; 5; 6; 7}",
    B: "x ∈ {-9; -8; -7; …; 5; 6; 7}",
    C: "x ∈ {-10; -9; -8; -7}",
    D: "x ∈ {7; 8; 9; 10}",
    answer: 3,
  },
  {
    question: "Cho tập hợp J = {x ∈ Z | -13 < x < -12}. J có mấy phần tử?",
    A: "1 phần tử",
    B: "2 phần tử",
    C: "3 phần tử",
    D: "0 phần tử",
    answer: 4,
  },
  {
    question:
      "Cho M = {-8; 5; -4; 0; 3}. Viết tập hợp N gồm các phần tử thuộc M và là số nguyên dương.",
    A: "N = {5; 0; 3}",
    B: "N = {5; 3}",
    C: "N = {-8; -4}",
    D: "N = {-8; -4; 0}",
    answer: 2,
  },
  {
    question: "Số đối của các số -10; 9; 0; 6; -42 lần lượt là:",
    A: "-10; 9; 0; 6; -42",
    B: "10; -9; 0; -6; 42",
    C: "10; 9; 0; 6; 42",
    D: "10; -9; -6; 42",
    answer: 2,
  },
  {
    question: "Số nào có số đối là chính nó?",
    A: "1",
    B: "-1",
    C: "0",
    D: "5",
    answer: 3,
  },
  {
    question:
      "Cho các số -10; -6; 2; 6; 16. Tìm hai số trong các số đã cho để tổng của chúng bằng 0.",
    A: "10 và 16",
    B: "6 và -6",
    C: "2 và 6",
    D: "10 và 16",
    answer: 2,
  },
  {
    question: "Số đối của các số nguyên -12 và 9 thứ tự là:",
    A: "-12 và 9",
    B: "12 và -9",
    C: "12 và 9",
    D: "-12 và -9",
    answer: 2,
  },
  {
    question:
      "Một chiếc tàu ngầm đang ở độ cao -25m so với mực nước biển, tiếp tục lặn xuống 35m nữa. Khi đó độ cao của tàu đó so với mực nước biển là:",
    A: "-10m",
    B: "60m",
    C: "-60m",
    D: "-35m",
    answer: 3,
  },
  {
    question:
      "Nhiệt độ phòng đông lạnh của một công ty thủy sản đang là -6<sup>o</sup>C. Bác An đã điều chỉnh giảm thêm 7<sup>o</sup>C. Hỏi khi đó nhiệt độ phòng đông lạnh là bao nhiêu?",
    A: "-1<sup>o</sup>C",
    B: "-13<sup>o</sup>C",
    C: "1 <sup>o</sup>C",
    D: "13 <sup>o</sup>C",
    answer: 2,
  },
  {
    question: "Trong tập hợp các số nguyên Z, cách tính đúng là:",
    A: "10 -13 = 3",
    B: "10 -13 = -3",
    C: "10 -13 = -23",
    D: "10 -13 không trừ được",
    answer: 2,
  },
  {
    question:
      "Bạn An nói rằng (-35) + 53 = 0; bạn Hòa nói rằng 676 + (-891) > 0. Chọn câu đúng.",
    A: "Bạn An đúng, bạn Hòa sai",
    B: "Bạn An sai, bạn Hòa đúng",
    C: "Bạn An và bạn Hòa đều đúng",
    D: "Bạn An và bạn Hòa đều sai",
    answer: 4,
  },
  {
    question: "Chọn khẳng định đúng:",
    A: "Số đối của 5 là 5",
    B: "Số đối của -5 là -5",
    C: "Số đối của 0 là 0",
    D: "Số đối của   là 3",
    answer: 3,
  },
  {
    question:
      "Nhiệt độ hiện tại của phòng đông lạnh là -2°C. Nếu nhiệt độ giảm 7°C, nhiệt độ tại phòng đông lạnh sẽ là bao nhiêu?",
    A: "5°C",
    B: "-9°C",
    C: "-5°C",
    D: "9°C",
    answer: 2,
  },
  {
    question: "Chọn đáp án đúng?",
    A: "(-10) + (-5) < -16",
    B: "3 + 5 < -3",
    C: "(-8) + (-7) = (-7) + (-8)",
    D: "(-102) + (-5) > -100",
    answer: 3,
  },
  {
    question: "Giá trị của biểu thức a + (-45) với a = -25 là:",
    A: "-70",
    B: "-25",
    C: "25",
    D: "70",
    answer: 1,
  },
  {
    question: "Kết quả của phép tính (-243) + (-27)",
    A: "-50",
    B: "50",
    C: "150",
    D: "-270",
    answer: 4,
  },
  {
    question: "Chọn câu sai:",
    A: "(-2) + (-5) > 0",
    B: "(-3)  + (-4) =  (-2) + (-5)",
    C: "(-6) + (-1) < -6",
    D: "(-1) + (-2) = (-3)",
    answer: 1,
  },
  {
    question: "Chọn đáp án đúng nhất:",
    A: "(-21) + 4 + (-55) = 4 + (-21) + (-55)",
    B: "(-21) + 4 + (-55) = (-55) + 4 + (-21)",
    C: "(-21) + 4 + (-55) = 4 + (-55) + (-21)",
    D: "Cả A, B, C đều đúng.",
    answer: 4,
  },
  {
    question: "Tính giá trị của biểu thức x + (-16) , biết x = -27:",
    A: "-43",
    B: "-11",
    C: "11",
    D: "43",
    answer: 1,
  },
  {
    question: "Kết quả của phép tính (-151) + (-28) + (-49)",
    A: "-282",
    B: "228",
    C: "280",
    D: "-228",
    answer: 4,
  },
  {
    question: "Kết quả của phép tính (-23) + (-40) + (-17) là:",
    A: "-70",
    B: "46",
    C: "80",
    D: "-80",
    answer: 4,
  },
  {
    question:
      "Bạn Nam nói rằng 189 + (-189) = 0; bạn Mai nói rằng 189 + (-198) < 0. Chọn câu đúng.",
    A: "Bạn Nam đúng, bạn Mai sai",
    B: "Bạn Nam sai, bạn Mai đúng",
    C: "Bạn Nam và bạn Mai đều đúng",
    D: "Bạn Nam và bạn Mai đều sai.",
    answer: 3,
  },
  {
    question: "Viết -17 thành tổng hai số nguyên khác dấu:",
    A: "-2 + (-15)",
    B: "-2 + 19",
    C: "2 + (-19)",
    D: "-5 + (-12)",
    answer: 3,
  },
  {
    question:
      "Một phòng đông lạnh có nhiệt độ là 5°C . Nhiệt độ của phòng đông lạnh là bao nhiêu nếu nhiệt độ giảm 7°C ?",
    A: "12°C",
    B: "2°C",
    C: "-2°C",
    D: "-12°C",
    answer: 3,
  },
  {
    question: "Thay * bằng chữ số thích hợp để 38 + (-2*) = 16.",
    A: "2",
    B: "4",
    C: "6",
    D: "8",
    answer: 1,
  },
  {
    question: "Giá trị nào của x thỏa mãn x -589 = (-335).",
    A: "x = -452",
    B: "x = -254",
    C: "x = 542",
    D: "x = 254",
    answer: 4,
  },
  {
    question: "Tổng a -(b -c -d) bằng:",
    A: "a -b -c -d",
    B: "a + b -c -d",
    C: "a -b + c + d",
    D: "a + b + c + d",
    answer: 3,
  },
  {
    question: "Tổng (-43567 -123) + 43567 bằng:",
    A: "-123",
    B: "-124",
    C: "-125",
    D: "87011",
    answer: 1,
  },
  {
    question: "Chọn câu đúng:",
    A: "170 - 228  = 58",
    B: "228 -892 < 0",
    C: "782 -783 > 0",
    D: "675 -908 > -3",
    answer: 2,
  },
  {
    question: "Chọn đáp án đúng?",
    A: "(-10) + (-5) < -16",
    B: "3 + 5 < -3",
    C: "(-8) + (-7) = (-7) + (-8)",
    D: "(-102) + (-5) > -100",
    answer: 3,
  },
  {
    question: "So sánh (-32) + (-14) và -45",
    A: "(-32) + (-14)  > -45",
    B: "-45 < (-32) + (-14)",
    C: "(-32) + (-14) < - 45",
    D: "(-32) + (-14) = -45",
    answer: 3,
  },
  {
    question: "Tìm x biết x -(-78) = (-12)",
    A: "x = 90",
    B: "x = -40",
    C: "x = -90",
    D: "x = 40",
    answer: 3,
  },
  {
    question:
      "So sánh kết quả hai biểu thức sau: A = -(12 -25) và B = (-12 + 25)",
    A: "A > B",
    B: "A < B",
    C: "A = B",
    D: "A < B < 0",
    answer: 3,
  },
  {
    question: "Tính nhanh các tổng sau: S = (86 -9 989) + 9 989",
    A: "86",
    B: "9 989",
    C: "-86",
    D: "-9 903",
    answer: 1,
  },
  {
    question: "Thực hiện phép tính sau: 4 + (-56) + (-4) + 60",
    A: "64",
    B: "4",
    C: "-4",
    D: "-54",
    answer: 2,
  },
  {
    question: "Kết quả của phép tính 554 + [94 + (-554) + (-14)] là:",
    A: "32",
    B: "24",
    C: "-130",
    D: "80",
    answer: 4,
  },
  {
    question: "Tìm x biết (-12) + x = (-15) -(-87)",
    A: "84",
    B: "-84",
    C: "-114",
    D: "-90",
    answer: 1,
  },
  {
    question:
      "Tìm khoảng cách giữa hai điểm a và b trên trục số, biết rằng a = -12, b = 12",
    A: "24",
    B: "0",
    C: "6",
    D: "10",
    answer: 1,
  },
  {
    question: "Tìm số nguyên x biết rằng (-14) -x + (-15) = -10",
    A: "x = 12",
    B: "x = -25",
    C: "x = -19",
    D: "x = -30",
    answer: 3,
  },
  {
    question: "Tích (-4)2 . (-2) bằng:",
    A: "-16",
    B: "16",
    C: "-32",
    D: "32",
    answer: 3,
  },
  {
    question: "Tính (36 -16) . (-5) + 6 . (-14 -6), ta được:",
    A: "-220",
    B: "-20",
    C: "20",
    D: "220",
    answer: 1,
  },
  {
    question: "Giá trị của biểu thức (x -2)(x -3) tại x = -1 là:",
    A: "-12",
    B: "12",
    C: "-2",
    D: "2",
    answer: 2,
  },
  {
    question: "Tính nhanh (-5) . 125 . (-8) . 20 . (-2) ta được kết quả là:",
    A: "-200 000",
    B: "-2 000 000",
    C: "200 000",
    D: "-100 000",
    answer: 1,
  },
  {
    question:
      "Khi x = -12, giá trị của biểu thức (x -8).(x + 7) là số nào trong bốn số sau:",
    A: "-100",
    B: "100",
    C: "-96",
    D: "-196",
    answer: 2,
  },
  {
    question: "Giá trị của biểu thức (27 -32) . x khi x = 8 là:",
    A: "-40",
    B: "-39",
    C: "-38",
    D: "-37",
    answer: 1,
  },
  {
    question: "Tính giá trị của biểu thức P = (x -3). 3 -20.x khi x = 5",
    A: "-94",
    B: "100",
    C: "-96",
    D: "-104",
    answer: 1,
  },
  {
    question: "Khẳng định nào sau đây đúng?",
    A: "(-2). (-3). 4. (-5) > 0",
    B: "(-2). (-3). 4. (-5) < 0",
    C: "(-2). (-3). 4. (-5) = 120",
    D: "(-2). (-3). 4. (-5) = 0",
    answer: 2,
  },
  {
    question: "Tính tổng hai tích sau: a = (-2). (-3) và c = (+3). (+2)",
    A: "a + c = 6",
    B: "a + c = 12",
    C: "a + c = -12",
    D: "a + c = -6",
    answer: 2,
  },
  {
    question: "Cho tập hợp B = {x  | 6 ⋮ x}. Tập hợp B có bao nhiêu phần tử?",
    A: "5",
    B: "8",
    C: "10",
    D: "12",
    answer: 2,
  },
  {
    question: "Kết quả của phép tính 23 -17 là:",
    A: "-40",
    B: "-6",
    C: "40",
    D: "6",
    answer: 4,
  },
  {
    question: "Tìm x biết 9 + x = 2.",
    A: "7",
    B: "-7",
    C: "11",
    D: "-11",
    answer: 2,
  },
  {
    question: "Giá trị của x thỏa mãn -15 + x = -20",
    A: "-5",
    B: "5",
    C: "-35",
    D: "15",
    answer: 1,
  },
  {
    question: "Số nguyên x thỏa mãn x -(15 -x) = x + 16 là:",
    A: "1",
    B: "31",
    C: "16",
    D: "-31",
    answer: 2,
  },
  {
    question: "Tìm số nguyên x biết tổng của ba số nguyên 15; -3 và x bằng 23.",
    A: "11",
    B: "-11",
    C: "25",
    D: "-25",
    answer: 1,
  },
  {
    question: "Số nguyên x nào dưới đây thỏa mãn x -8 = 20.",
    A: "x = 12",
    B: "x = 28",
    C: "x = 160",
    D: "x = -28",
    answer: 2,
  },
  {
    question: "Giá trị của biểu thức B = 8912 + x biết x = -6372 là:",
    A: "số nguyên dương nhỏ hơn 2000",
    B: "số nguyên dương lớn hơn 2000",
    C: "số 0",
    D: "số nguyên âm nhỏ hơn -100",
    answer: 2,
  },
  {
    question:
      "Đơn giản biểu thức x + 1 982 + 172 + (-1 982) -162 ta được kết quả là:",
    A: "x -10",
    B: "x + 10",
    C: "10",
    D: "x",
    answer: 2,
  },
  {
    question: "Chọn câu đúng:",
    A: "32 -89 > 0",
    B: "167 -176 = 0",
    C: "567 -566 > 0",
    D: "356 -166 > 300",
    answer: 3,
  },
  {
    question: "Sau khi phá ngoặc phép tính 4 -(12 -15) ta được",
    A: "4 -12 -15",
    B: "4 -12 + 15",
    C: "4 + 12 -15",
    D: "-4 -12 -15",
    answer: 2,
  },
  {
    question: "Tính (9-21) -(-91+10) ta được:",
    A: "65",
    B: "-72",
    C: "69",
    D: "79",
    answer: 3,
  },
  {
    question: "Tìm số nguyên y biết: y -345 -69 = -12",
    A: "y = 302",
    B: "y = 402",
    C: "y = 203",
    D: "y = 204",
    answer: 2,
  },
  {
    question: "Tính (55+23) -(-45 -77) ta được:",
    A: "-100",
    B: "64",
    C: "-52",
    D: "200",
    answer: 4,
  },
  {
    question: "Giá trị của biểu thức (23 + 19) + (-13 + 11) là:",
    A: "40",
    B: "3",
    C: "47",
    D: "-65",
    answer: 1,
  },
  {
    question: "Tính tổng 30 + 12 + (-20) + (-12)?",
    A: "16",
    B: "10",
    C: "-10",
    D: "-16",
    answer: 2,
  },
  {
    question: "Đơn giản biểu thức: x + 22 + (-14) + 52?",
    A: "x -50",
    B: "x + 60",
    C: "x + 50",
    D: "x -60",
    answer: 2,
  },
];
const hardInt =[
  {question:"Trong các số sau, số nguyên âm nào lớn nhất và số nguyên âm nào nhỏ nhất:-197; -86; -18; -4; -976; -118; -6; -91.",
    A:"-197 lớn nhất, -4 nhỏ nhất",
    B:"-4 lớn nhất, -976 nhỏ nhất",
    C:"-976 lớn nhất, -4 nhỏ nhất",
    D:"-4 lớn nhất, -197 nhỏ nhất",
    answer: 2
    },
    {question:"Số nguyên âm nhỏ nhất có 3 chữ số là:",
    A:"-111",
    B:"-000",
    C:"-100",
    D:"-999",
    answer: 4
    },
    {question:"Số nguyên âm lớn nhất có hai chữ số là:",
    A:"-99",
    B:"-11",
    C:"-10",
    D:"-00",
    answer: 3
    },
    {question:"Biết A = {-99;-98; … ; -3; -2; -1}. Số phần tử của tập A là:",
    A:"-99 phần tử",
    B:"99 phần tử",
    C:"100 phần tử",
    D:"-100 phần tử",
    answer: 2
    },
    {question:"Số phần tử của tập hợp C =  {-1000; -998; …; -4; -2} là:",
    A:"500 phần tử",
    B:"1000 phần tử",
    C:"100 phần tử",
    D:"-1000 phần tử",
    answer: 1
    },
    {question:"Cho tập hợp A = {-2; 0; 3; 6}. Tập hợp B gồm các phần tử là số đối của các phần tử trong tập hợp A là:",
    A:"B = {-2; 0; -3; -6}",
    B:"B = {2; 0; 3; 6}",
    C:"B = {-6; -3; 0; 2}",
    D:"B = {-2; 0; 3; 6}",
    answer: 3
    },
    {question:"Cho tập hợp A={-7;-4;-1;2;3}. Tập hợp B gồm các phần tử là số đối của các phần tử trong tập hợp A.", 
    A:"B = {7; 4; 1; -2; -3}",
    B:"B = {3; -2; 1; -5; 4; 7}",
    C:"B = {3; -2; 1; -5; 7}",
    D:"B = {7; 2; 1; -5; -7}",
    answer: 1 
    },
    {question:"Trên trục số điểm A cách gốc 5 đơn vị về phía bên trái, điểm B cách điểm A là 4 đơn vị về phía bên phải. Hỏi điểm B cách gốc bao nhiêu đơn vị?",
    A:"3",
    B:"5",
    C:"2",
    D:"1",
    answer: 4
    },
    {question:"Cho E = {3; -8; 0}. Tập hợp F gồm các phần tử của E và các số đối của chúng là?",
    A:"F = {3; 8;  0; -3}",
    B:"F = {-3; -8; 0}",
    C:"F = {3; -8; 0; -3}",
    D:"F  = {3; -8; 0; -3; 8}",
    answer: 4
    },
    {question:"Cho số nguyên x, biết điểm x cách điểm 0 là 6 đơn vị. Có bao nhiêu số nguyên thỏa mãn điều kiện trên?",
    A:"2",
    B:"3",
    C:"4",
    D:"5",
    answer: 1
    },
    {question:"Sắp xếp các số nguyên theo thứ tự tăng dần: -12, 3, 15, 12, -7, -6, 0. Thứ tự đúng là:",
    A:"-12, 3, 15, 12, -7, -6, 0",
    B:"-12; -7; -6; 0; 3; 12; 15",
    C:"-0; 3; -6; -7; -12; 12; 15",
    D:"15; 12; 3; 0; -6; -7; -12",
    answer: 2
    },
    {question:"Hãy sắp xếp các số sau theo thứ tự tăng dần: -3; +4; 7; -7;0; -1",
    A:"-7; -3; -1; 0; +4; 7",
    B:"7; +4; 0; -1; -3; -7",
    C:"7; -7; +4; -3; -1; 0",
    D:"0; -1; -3; +4; -7; 7",
    answer: 1
    },
    {question:"Cho E = {-4; 2; 0; -1; 7; -2020}. Viết tập hợp D gồm các phần tử thuộc E và là số nguyên âm.",
    A:"D = {-4; 2; -1}",
    B:"D = {-4 ; -1; -2020}",
    C:"D = {-1; 7; 2020}",
    D:"D = {2; 0; 7}",
    answer: 2
    },
    {question:"Có bao nhiêu số nguyên nằm giữa - 4 và 5 là",
    A:"6",
    B:"5",
    C:"8",
    D:"7",
    answer: 3
    },
    {question:"Các số nguyên âm nằm giữa -3 và 2 là:",
    A:"-2; -1",
    B:"-2; -1; 0; 1",
    C:"-3; -2; -1; 0; 1; 2",
    D:"0;1",
    answer: 1
    },
    {question:"Có bao nhiêu số nguyên nằm giữa -3 và 4",
    A:"3",
    B:"5",
    C:"6",
    D:"7",
    answer: 3
    },
    {question:"Trên trục số điểm A cách gốc 4 đơn vị về phía bên trái, điểm B cách gốc 1 đơn vị về phía bên phải. Hỏi điểm A cách điểm B bao nhiêu đơn vị?",
    A:"3",
    B:"5",
    C:"2",
    D:"4",
    answer: 2 
    },
    {question:"Tổng tất cả các số nguyên n thoả mãn -2 < n   2 là:",
    A:"0",				
    B:"2",				
    C:"-2",				
    D:"4",
    answer: 2
    },
    {question:"Nếu x - 1 là số nguyên âm lớn nhất thì x bằng?",
    A:"0",
    B:"-1",
    C:"-2",
    D:"1",
    answer: 1
    },
    {question:"Tổng của số nguyên âm lớn nhất và số nguyên dương nhỏ nhất là",
    A:"1",
    B:"-1",
    C:"0",
    D:"Không tính được",
    answer: 3
    },
    {question:"Nếu x - 3 là số nguyên âm lớn nhất, y + 9 là số nguyên dương nhỏ nhất thì x + y bằng:",
    A:"12",
    B:"6",
    C:"0",
    D:"-6",
    answer: 4
    },
    {question:"Trên trục số điểm nào tạo với hai điểm -1 và 2 bộ ba số cách đều nhau?",
    A:"-4",
    B:"5",
    C:"0 hoặc 1",
    D:"-4 hoặc 5",
    answer: 4
    },
    {question:"Số các phần tử của tập hợp A = { -999; -998; …; 1; 2; 3} là:",
    A:"1001 phần tử",
    B:"999 phần tử",
    C:"1002 phần tử",
    D:"1003 phần tử",
    answer: 4
    },
    {question:"Tổng S = (-1000) + (-999) + (-998) + … + 999 có kết quả là bao nhiêu?",
    A:"-1000",
    B:"0",
    C:"1000",
    D:"999",
    answer: 1
    },
    {question:"Số các phần tử của tập hợp B = {-100; -99; … 99; 100}",
    A:"200 phần tử",
    B:"201 phần tử",
    C:"199 phần tử",
    D:"202 phần tử",
    answer: 2
    },
    {question:"Sắp xếp các số sau theo thứ tự giảm dần: 0; -2; 5; 7; -1; -8",
    A:"7; 5; 0; -1; -2; -8",
    B:"-1; -2; -8; 0; 5; 7",
    C:"-8; -2; -1; 0; 5; 7",
    D:"-8; -2; 0; -1; 5; 7",
    answer: 1
    },
    {question:"Tìm các số nguyên x thỏa mãn - 12 < x < 13. Có bao nhiêu số nguyên như vậy?",
    A:"23",	
    B:"24",	
    C:"25",	
    D:"26",
    answer: 2
    },
    {question:"Có bao nhiêu số nguyên x thỏa mãn -3 < x ≤ 3?",
    A:"5",	
    B:"4",	
    C:"3",	
    D:"6", 
    answer: 4
    },
    {question:"Sử dụng số nguyên âm để diễn tả nhiệt độ Mùa đông ở Moscow có nhiệt độ trung bình tháng 12 là 50⁰C dưới 0⁰C.",
    A:"50⁰C",	
    B:"-50⁰C",	
    C:"12⁰C",	
    D:"-12⁰C",
    answer: 2
    },
    {question:"Biết - 9 < x < 0. Tập hợp các số nguyên x thỏa mãn:",
    A:"A = {-8; -7; -6; -5; -4; -3; -2; -1}",
    B:"A = {-9; -8; -7; -6; -5; -4; -3; -2; -1}",
    C:"A = {-9; -8; -7; -6; -5; -4; -3; -2; -1; 0}",
    D:"A = {-8; -7; -6; -5; -4; -3; -2; -1; 0}",
    answer: 1
    },
    {question:"Cho tập hợp H={a∈Z|-2≤a<1}. Tập hợp K gồm các phần tử là số đối của các phần tử của H là:",
    A:"K = {0; 1; 2}",
    B:"K = {-2; -1; 0}",
    C:"K = {0; 1}",
    D:"Q = {-2; -1; 0; 1; 2}", 
    answer: 1
    },
    {question:"Tổng các số nguyên x thỏa mãn điều kiện -10≤x≤9 là:",
    A:"0", 			
    B:"-9",			
    C:"-10", 				
    D:"-1",
    answer: 3
    },
    {question:"Số đối của số |-100| là?",
    A:"-100",
    B:"100",
    C:"0",
    D:"200",
    answer: 1
    },
    {question:"Cho tập hợp E gồm các số nguyên không lớn hơn 8. Tập E có bao nhiêu số không phải là số nguyên âm?",
    A:"8 số",
    B:"7 số",
    C:"9 số",
    D:"10 số",
    answer: 3
    },
    {question:"Điểm a đang ở vị trí -4 trên trục số. Sau khi dịch chuyển a về bên phải 5 đơn vị rồi dịch sang bên trái 2 đơn vị thì a nằm ở vị trí nào?",
    A:"-1",
    B:"1",
    C:"-4",
    D:"2",
    answer: 1
    },
    {question:"Một người xuất phát từ A, đi về hướng Bắc 4km, rồi đi về hướng Nam 10km. Khi đó người ấy cách điểm xuất phát A là:",
    A:"14km",
    B:"4km",
    C:"10km",
    D:"6km",
    answer: 4
    },
    {question:"Tìm số nguyên x, biết:   là số nguyên âm lớn nhất",
    A:"109",
    B:"10",
    C:"100",
    D:"-10",
    answer: 2
    },
    {question:"Tìm số nguyên x, biết: là số nguyên âm nhỏ nhất có hai chữ số.", 
    A:"-102",
    B:"102",
    C:"100",
    D:"-100",
    answer: 1
    },
    {question:"Tìm giá trị nhỏ nhất của biểu thức:  ",
    A:"2",
    B:"3",
    C:"-3",
    D:"8",
    answer: 3
    },
    {question:"Tìm năm số nguyên liên tiếp có tổng bằng 0.",
    A:"-2; -1; 0; 1; 2",
    B:"-4; -1; 0; 1; 4",
    C:"-5; -1; 0; 1; 5",
    D:" 4; -3; 0; 3; 4",
    answer: 1
    },
    {question:"Sắp xếp các số nguyên: -11; 8; 12; -14; 0 theo thứ tự giảm dần là:",
    A:"-14; 12; -11; 8; 0",
    B:"-14; -11; 0; 8; 12",
    C:"12; 8; 0; -11; -14",
    D:"12; 8; 0; -14; -11",
    answer: 3
    },
    {question:"Tổng các số nguyên x mà  là:",
    A:"0",			
    B:"-3",		
    C:"3",			
    D:"6",
    answer: 3
    },
    {question:"Một chiếc diều cao 30m (so với mặt đất), sau một lúc độ cao của diều tăng lên 7m rồi sau đó giảm 4m. Hỏi cuối cùng diều ở độ cao bao nhiêu mét so với mặt đất?",
    A:"27m",
    B:"41m",
    C:"33m",
    D:"34m",
    answer: 3
    },
    {question:"Cho số nguyên x sao cho - 5 < x < -2. Tổng các giá trị của x là:",
    A:"-7",                                      
    B:"-14",                          
    C:"0",                               
    D:"7",
    answer: 1
    },
    {question:"Cho các số nguyên: 1; 3; -3; -5. Cách sắp xếp nào sau đây là đúng?",
    A:"-3 < -5 < 1 < 3",
    B:"-5 < -3 < 1 < 3",
    C:"1 < -3 < -5 < 3",
    D:"1 < 3 < -3 < -5",
    answer: 2
    },
    {question:"Tìm tổng các số nguyên x, biết: -5 < x < 5",
    A:"2",
    B:"1",
    C:"0",
    D:"3",
    answer: 3
    },
    {question:"Tập hợp nào có các số nguyên được xếp theo thứ tự tăng dần",
    A:"{2; -17; 5; 1; -2; 0}",
    B:"{-2; -17; 0; 1; 2; 5}",
    C:"{0; 1; -2; 2; 5; -17}",
    D:"{-17; -2; 0; 1; 2; 5}",
    answer: 4
    },
    {question:"  thì x bằng:",  
    A:"x không có giá trị nào",
    B:"0",
    C:"7",
    D:"-7",
    answer: 1
    },
    {question:" thì x bằng",
    A:"x không có giá trị nào",
    B:"-10",
    C:"10",
    D:"0",
    answer: 4
    },
    {question:"a là số nguyên dương nhỏ nhất có 2 chữ số, b là số nguyên âm lớn nhất. Tính tổng a và b",
    A:"10",
    B:"-1",
    C:"9", 
    D:"11",
    answer: 3
    },
    {question:"Kết quả của tổng 161 + [27 + (- 161) + (- 87)] là:",
    A:"- 60",
    B:"60",
    C:"80",
    D:"- 80",
    answer: 1
    },
    {question:"Giá trị của biểu thức 2a - (-125)  với a = 12 là:",
    A:"149",
    B:"-149",
    C:"101",
    D:"-101",
    answer: 1
    },
    {question:"Nhiệt độ ở thủ đô Ottawa, Canada lúc 7 giờ là -4<sup>o</sup>C, đến 10 giờ tăng thêm 6<sup>o</sup>C. Nhiệt độ ở Ottawa lúc 10 giờ là bao nhiêu?",
    A:"-2<sup>o</sup>C",
    B:"2<sup>o</sup>C",
    C:"-10<sup>o</sup>C",
    D:"10<sup>o</sup>C",
    answer: 2
    },
    {question:"Nhiệt độ ở thủ đô Ottawa, Canada lúc 6 giờ là -6<sup>o</sup>C, đến 9 giờ tăng thêm 3<sup>o</sup>C. Nhiệt độ ở Ottawa lúc 9 giờ là bao nhiêu?",
    A:"-3<sup>o</sup>C",
    B:"3<sup>o</sup>C",
    C:"-9<sup>o</sup>C",
    D:"9<sup>o</sup>C",
    answer: 1
    },
    {question:"Tìm tổng tất cả các số nguyên x, biết: - 4 < x < 5 ?",
    A:"1",
    B:"5",
    C:"4",
    D:"3",
    answer: 3
    },
    {question:"Tìm x ∈ Z, biết: x + (- 27) = (- 100) + 73",
    A:"x = - 1",
    B:"x = 0",
    C:"x = 1",
    D:"x = 2",
    answer: 2
    },
    {question:"Tìm tổng các số nguyên x biết -4 < x < 3",  
    A:"4",
    B:"-4",
    C:"-3",
    D:"0",
    answer: 3
    },
    {question:"-176 -13.4 + 125 : 5 là",
    A:"-228",
    B:"-203",
    C:"203",
    D:"218",
    answer: 2
    },
    {question:"Tính tổng của tất cả các số nguyên x thỏa mãn -100  < x < 100",
    A:"100",
    B:"0",
    C:"99",
    D:"-100",
    answer: 2
    },
    {question:"Tính tổng của tất cả các số nguyên x thỏa mãn -99  < x < 100",
    A:"100",
    B:"0",
    C:"-99",
    D:"99",
    answer: 4
    },
    {question:"Chọn câu đúng:",
    A:"(-7) + 1100 + (-13) + (-1100) = 20",     
    B:"(-7) + 1100 + (-13) + (-1100) = -20",
    C:"(-7) + 1100 + (-13) + (-1100) = 30",     
    D:"(-7) + 1100 + (-13) + (-1100) = -10",
    answer: 2
    },
    {question:"Biểu thức a - (b + c - d) + (-d) - a khi bỏ ngoặc là:",
    A:"-b - c",
    B:"-b -c - d",
    C:"-b - c + 2d",
    D:"-b - c -2d",
    answer: 1
    },
    {question:"Cho số nguyên b và b - x = - 9. Tìm x.",
    A:"- 9 - b",     
    B:"- 9 + b",     
    C:"b + 9",     
    D:"- b + 9",
    answer: 3
    },
    {question:"Tính hợp lý (- 1 215) - (- 215 + 115) - (- 1 115) ta được:",
    A:"- 2 000",     
    B:"2 000",     
    C:"0",     
    D:"1 000",
    answer: 3
    },
    {question:"Tính M = 90 - (-113) - 78 ta được:",
    A:"M > 100",
    B:"M < 50",
    C:"M < 0",
    D:"M > 150",
    answer: 1
    },
    {question:"Giá trị của P = 2001 - (53 + 1579) - (-53) là:",
    A:"là số nguyên âm",
    B:"là số nguyên dương",
    C:"là số nhỏ hơn -2",
    D:"là số nhỏ hơn 100",
    answer: 2
    },
    {question:"Tổng các số nguyên âm nhỏ nhất có 4 chữ số và số nguyên âm lớn nhất có 5 chữ số là:",
    A:"-19999",
    B:"10999",
    C:"-10090",
    D:"-1199",
    answer: 1
    },
    {question:"Bỏ dấu ngoặc rồi tính: (77 + 22 - 65) -(67 + 12 -75)", 
    A:"10",	
    B:"20",	
    C:"30",	
    D:"40",
    answer: 3
    },
    {question:"Điền hai số tiếp theo vào dãy số sau: - 2; 4; - 8; 16; ...",
    A:"32 và 64",
    B:"- 32 và 64",
    C:"32 và - 64",
    D:"- 32 và - 64",
    answer: 2
    },
    {question:"Giá trị của biểu thức Q = (-5)5. (-23)2 . 0. (2020)2020 là:",
    A:"-34792",
    B:"1",
    C:"0",
    D:"100 000",
    answer: 3
    },
    {question:"Giá trị của biểu thức (- 63) . (1 - 299) - 299 . 63 là:",
    A:"- 63",
    B:"63",
    C:"- 53",
    D:"53",
    answer: 1
    },
    {question:"Giá trị của m . n2 với m = 3, n = - 5 là:",
    A:"- 30",
    B:"30",
    C:"- 75",
    D:"75",
    answer: 4
    },
    {question:"Giá trị biểu thức M = (- 192 873) . (- 2 345) . (- 4)5 . 0 là:",
    A:"- 192 873",     
    B:"1",
    C:"0",     
    D:"(- 192 873) . (- 2 345) . (- 4)5",
    answer: 3
    },
    {question:"Giá trị của x thỏa mãn - 2(x - 5) < 0 là:",
    A:"x = 3",
    B:"x = 4",
    C:"x = 5",
    D:"x = 6",
    answer: 4
    },
    {question:"Giá trị của x thỏa mãn 2(x - 5) < 0 là:",
    A:"x = 4",
    B:"x = 5",
    C:"x = 6",
    D:"x = 7",
    answer: 1
    },
    {question:"Tính hợp lý: A = -43 . 18 - 82 . 43 - 43 . 100",
    A:"0",
    B:"-86000",
    C:"-8600",
    D:"-4300",
    answer: 3
    },
    {question:"Tính hợp lý: B = -55. 78 + 13. (-78) - 78. (-65)",
    A:"1",
    B:"234",
    C:"-234",
    D:"130",
    answer: 3
    },
    {question:"Tìm x, biết: (x - 12). (8 + x) = 0",
    A:"x = 12",
    B:"x = 8",
    C:"x = 12 hoặc x =  -8",
    D:"x = 0 hoặc x = 12",
    answer: 3
    },
    {question:"Thực hiện phép tính: (-8). (-8). (-8). (-8) - 84 + 105",
    A:"2. 84",	
    B:"84 + 10",	
    C:"0",	
    D:"105",
    answer: 4
    },
    {question:"Tìm số nguyên x thỏa mãn: (x - 6). (x - 3) = 0",                       
    A:"x = 6",		
    B:"x = 3",
    C:"x = -6, x = -3",		
    D:"x = 6, x = 3",   
    answer: 4
    },
    {question:"So sánh hai phép tính sau: A = (-3). (-5). (-7). (-9). (-11) và B = (-9). (-11)",
    A:"A ≥ B",	
    B:"A = B",	
    C:"A < B",	
    D:"A > B",
    answer: 3
    },
    {question:"Tìm số nguyên x, y biết: (x -25). (y + 5) = 0",
    A:"x = 25 và y = -5",
    B:"x = 25 và y ∈ Z",
    C:"x ∈ Z và y = -5",
    D:"Tất cả đáp án trên",
    answer: 4
    },
    {question:"Tính giá trị của biểu thức x -2 + x -2 + x -2 + x -2 + x -2 tại x = -7",
    A:"- 30",           	
    B:"30",             	 
    C:"- 45",                	
    D:"45",
    answer: 3
    },
    {question:"Có bao nhiêu giá trị x thỏa mãn (x -6). (x2 + 2) = 0",
    A:"0",	
    B:"2",	
    C:"3",	
    D:"1",
    answer: 4
    },
    {question:"Tìm x ∈ Z biết (2x -3)2 = 25",
    A:"x = -4 hoặc x = -1",	
    B:"x = -4",	
    C:"x = -1", 	
    D:"x = -1 hoặc x = 4",
    answer: 4
    },
    {question:"Tìm số nguyên x biết 34 - (25 + 34) = x - (25 - 9)",
    A:"10",
    B:"- 10",
    C:"9",
    D:"- 9",
    answer: 4
    },
    {question:"Đơn giản biểu thức (- 65) - (x + 35) + 101",
    A:"x",
    B:"x - 1",
    C:"1 - x",
    D:"- x",
    answer: 3
    },
    {question:"A = 56 + 27 -11 -28 + 84 bằng với biểu thức nào dưới đây?",
    A:"56 + 27 -(11 -28 + 84)",
    B:"(56 -27) -(11 -28 + 84)",
    C:"(56 + 27) -(11 + 28 -84)",
    D:"(56 -27) -(11 + 28 -84)",
    answer: 3
    },
    {question:"Thu gọn các tổng sau: M = - (a - b - c) - (-a + b + c) - (a - b + c)",
    A:"M = a + b + c",
    B:"M = -a + b + c",
    C:"M = -a + b - c",
    D:"M = a + b - c",
    answer: 3
    },
    {question:"Tính giá trị biểu thức: (-314) - (75 + x) nếu x = 25",
    A:"- 214",	
    B:"- 414",	
    C:"- 314",	
    D:"- 404",
    answer: 2
    },
    {question:"Giá trị của biểu thức -(32 + 14) -(-14 + 68) là",
    A:"86",	
    B:"-54",	
    C:"-100",	
    D:"34",
    answer: 3
    },
    {question:"Tính nhanh tổng sau: (-2002) -(57 -2002)",
    A:"47",	
    B:"-57",	
    C:"57",	
    D:"-47",
    answer: 2
    },
    {question:"Giá trị của biểu thức -(76 + 139) -(24 -39) là:",
    A:"63",	
    B:"145",	
    C:"-200",	
    D:"-15",
    answer: 3
    },
    {question:"Cho a = -13, b = 25, c = -30. Tính giá trị của biểu thức: 25 + a - (b + c) - a",
    A:"39",	
    B:"30",	
    C:"20",	
    D:"4",
    answer: 2
    },
    {question:"Tìm số nguyên x biết: - (x - 6 + 85) = (x + 51) - 54",    
    A:"x = -38",	
    B:"x = 38",	
    C:"x = 15",	
    D:"x = 14",
    answer: 1
    },
    {question:"Tìm số nguyên x biết:  - (35 - x) - (37 - x) = 33 - x",
    A:"x = -35",	
    B:"x = 35",	
    C:"x = 105",	
    D:"x = -105",
    answer: 2
    },
    {question:"Tổng các số nguyên âm nhỏ nhất có 3 chữ số và số nguyên âm lớn nhất có 3 chữ số là?",
    A:"-1 099",	
    B:"1 099",	
    C:"-1 009",	
    D:"-1 199",
    answer: 1
    },
    {question:"Tháng 10, cửa hàng lãi được 10 triệu đồng, tháng 11 lỗ 3 triệu đồng, tháng 12 lãi 5 triệu đồng. Hỏi sau ba tháng, cửa hàng đó lãi hay lỗ được bao nhiêu?",
    A:"Lỗ 2 triệu đồng",
    B:"Lãi 12 triệu đồng",
    C:"Lãi 8 triệu đồng",
    D:"Lỗ 8 triệu đồng",
    answer: 2
    },
    {question:"a là số nguyên âm. a2022 là số",
    A:"Số nguyên âm",
    B:"Số nguyên dương",
    C:"0",
    D:"Số âm",
    answer: 2
    },
    {question:"a là số nguyên âm. a2023 là số",
    A:"Số nguyên âm",
    B:"Số nguyên dương",
    C:"0",
    D:"Số tự nhiên",
    answer: 1
    },    
]
const easyFloat =[
  {question:"Tính: 63 548 + 19 256",
    A:"82 804",
    B:"84 804",
    C:"88 402",
    D:"84 40",
    answer: 1
    },
    {question:"Kết quả của phép tính: 2 346 + 3 457 là",
    A:"5 703",
    B:"5 803",
    C:"5 793",
    D:"5 903",
    answer: 2
    },
    {question:"Cho phép trừ: 367 - 59, chọn kết luận đúng",
    A:"367 là số trừ",
    B:"59 là số bị trừ", 
    C:"59 là hiệu",
    D:"367 là số bị trừ",
    answer: 4
    },
    {question:"Kết quả của phép trừ 23 456 - 14 267 là:",
    A:"9 189",
    B:"9 198",
    C:"10 198", 
    D:"10 928",
    answer: 1
    },
    {question:"Cho phép tính: 2 342 + 123 = 2 465. Chọn câu sai:",
    A:"2 342 được gọi là số hạng",
    B:"123 được gọi là số hạng",
    C:"2 465 được gọi là tổng",
    D:"2 342 được gọi là tổng",
    answer: 4
    },
    {question:"Một số tự nhiên a bất kì cộng với số 0 thì:",
    A:"bằng a",
    B:"bằng a + 1",
    C:"bằng a - 1",
    D:"bằng a + 2",
    answer: 1
    },
    {question:"5125 + 456 875 bằng",
    A:"46 200",
    B:"462 000",
    C:"46 300",
    D:"426 000",
    answer: 2
    },
    {question:"15 946 + ? = 51 612 + 15 946. Điền số thích hợp vào dấu ?",
    A:"51 612", 
    B:"15 946",
    C:"67 558",
    D:"35 666",
    answer: 1
    },
    {question:"Khẳng định nào sau đây sai?",
    A:"a + b + c = (a + b) + c",
    B:"a + b + c = (a + c) + b",
    C:"a + b + c = (a + b) + b",
    D:"a + b + c = a + (b + c)",
    answer: 3
    },
    {question:"Cho phép tính 789 - 541. Chọn câu sai trong các câu sau?",
    A:"541 là số trừ",
    B:"541 là số bị trừ",
    C:"789 là số bị trừ",
    D:"248 là hiệu",
    answer: 2
    },
    {question:"So sánh kết quả a + b và b + a",
    A:"a + b = b + a",
    B:"a + b ≥ b + a",
    C:"a + b < b + a",
    D:"a + b ≤ b + a",
    answer: 1
    },
    {question:"So sánh kết quả (a + b) + c và a + (b + c)",
    A:"(a + b) + c > a + (b + c)",
    B:"(a + b) + c = a + (b + c)",
    C:"(a + b) + c ≥ a + (b + c)",
    D:"(a + b) + c ≤ a + (b + c)",
    answer: 2
    },
    {question:"Trong phép tính 456 - 34 = 422. Thì 422 là",
    A:"Số trừ",
    B:"Hiệu",
    C:"Tổng",
    D:"Số bị trừ",
    answer: 2
    },
    {question:"Trong phép tính 84 + 123 = 207. Số 123 là",
    A:"Tích",
    B:"Thừa số",
    C:"Số hạng",
    D:"Tổng",
    answer: 3
    },
    {question:"Thay ? bằng số thích hợp: 5 982 + ? = 9 875 + 5 982",
    A:"9 758",	
    B:"9 578",	
    C:"9 785",	
    D:"9 875",
    answer: 4
    },
    {question:"6 + 6 + 6 + 6 = ?",
    A:"6",
    B:"6.2",
    C:"6.4",
    D:"64",
    answer: 3
    },
    {question:"Tích 4.a.b.c bằng",
    A:"4", 
    B:"4ab",
    C:"4 + abc",
    D:"4abc",
    answer: 4
    },
    {question:"Cho a, b, c là các số tự nhiên tùy ý. Khẳng định nào sau đây sai?",
    A:"abc = (ab)c",
    B:"abc = a(bc)",
    C:"abc = b(ac)",
    D:"abc = a + b + c",
    answer: 4
    },
    {question:"Cho phép tính 12 × 5 = 60. Chọn câu sai.", 
    A:"12 là thừa số", 
    B:"5 là thừa số",
    C:"60 là tích",
    D:"60 là thương",
    answer: 4
    },
    {question:"Cho phép tính: 10 789 : 123. Chọn kết luận đúng.",
    A:"Số 10 789 được gọi là số bị chia",
    B:"Số 123 được gọi là số bị chia",
    C:"Số 10 789 được gọi là số chia",
    D:"Số 123 được gọi là thương",
    answer: 1
    },
    {question:"Thương của phép chia số 785 cho số 5 là:",
    A:"157",
    B:"175",
    C:"177",
    D:"155",
    answer: 1
    },
    {question:"a : 1 = ?",
    A:"1",
    B:"2",
    C:"a",
    D:"0",
    answer: 3
    },
    {question:"Kết quả của phép tính 0 : a (với a ≠ 0) là:",
    A:"0", 
    B:"1",
    C:"2",
    D:"a",
    answer: 1
    },
    {question:"Kết quả của phép nhân hai số tự nhiên được gọi là",
    A:"Tổng",	
    B:"Hiệu",	
    C:"Tích",	
    D:"Thương",
    answer: 3
    },
    {question:"Cho phép chia 125: 25 = 5. Trong phép tính này thì 125 là:",
    A:"Số bị chia", 	
    B:"Số chia",	
    C:"Thương",	
    D:"Số dư",
    answer: 1
    },
    
    {question:"Phát biểu nào sau đây là sai?",
    A:"a.1 = 1.a = a",
    B:"a.0 = 0.a = a",
    C:"(ab) c = a (bc) = abc",
    D:"a (b + c) = ab + ac",
    answer: 2
    },
    {question:"Tính nhẩm 775.100",
    A:"77 500",	
    B:"7 500",	
    C:"875",	
    D:"12 050",
    answer: 1
    },
    {question:"Lũy thừa bậc n của số tự nhiên a được viết là:",
    A:"a<sup>n</sup>",	
    B:"a. n",	
    C:"a + n", 	
    D:"a - n",
    answer: 1
    },
    {question:"Cách đọc 4<sup>2</sup> nào là sai?",
    A:"Bốn lũy thừa hai",
    B:"Bốn nhân hai",
    C:"Bốn bình phương",
    D:"Bốn mũ hai",
    answer: 2
    },
    {question:"Hãy chỉ ra cơ số của lũy thừa 28<sup>4</sup>",
    A:"Cơ số là 4",
    B:"Cơ số là 28",
    C:"Cơ số là 284",
    D:"Cơ số là 428",
    answer: 2
    },
    {question:"Khi nhân hai lũy thừa cùng cơ số: a<sup>m</sup>. a<sup>n</sup>, kết quả là:",
    A:"a<sup>m.n</sup>",	
    B:"a<sup>m+n</sup>",	
    C:"a<sup>m-n</sup>",	
    D:"a<sup>m:n</sup>",
    answer: 2
    },
    {question:"Chọn phát biểu đúng.",
    A:"a<sup>3</sup> còn được gọi là a lập phương",
    B:"a<sup>3</sup> = a + a + a",
    C:"a<sup>3</sup> = a.3",
    D:"Số mũ của a<sup>3</sup> là a",
    answer: 1
    },
    {question:"Viết kết quả sau dưới dạng một lũy thừa: 6.6.6.6.6?",
    A:"6.5",	
    B:"6<sup>5</sup>",	
    C:"5<sup>6</sup>",	
    D:"6 + 5",
    answer: 2
    },
    {question:"Lập phương của 9 được viết như thế nào?",
    A:"9<sup>2</sup>",	
    B:"9.3",	
    C:"9<sup>3</sup>",	
    D:"3<sup>9</sup>",
    answer: 3
    },
    {question:"Bình phương của 5 được viết như thế nào?",
    A:"5.2",	
    B:"5<sup>3</sup>",	
    C:"5<sup>2</sup>",	
    D:"5. 3",
    answer: 3
    },
    {question:"Viết tích sau dưới dạng lũy thừa:  9 . 9. 9 . 9 . 9",
    A:"9<sup>5</sup>",
    B:"6<sup>6</sup>",
    C:"9<sup>4</sup>",
    D:"9<sup>6</sup>",
    answer: 1
    },
    {question:"1<sup>10</sup>  bằng:",
    A:"10",
    B:"11",
    C:"1",
    D:"0",
    answer: 3
    },
    {question:"Cơ số và số mũ của lũy thừa 2019<sup>2020</sup> lần lượt là:",
    A:"2019 và 2020",
    B:"2020 và 2019",
    C:"2019 và 2019<sup>2020</sup>",
    D:"2019<sup>2020</sup> và 2019",
    answer: 1
    },
    {question:"Chọn câu sai. 3<sup>8</sup> được đọc là:",
    A:"ba mũ tám",
    B:"ba lũy thừa tám",
    C:"lũy thừa bậc tám của ba",
    D:"tám mũ ba",
    answer: 4
    },
    {question:"Với a ≠ 0 và , ta có: a<sup>m</sup> : a<sup>n</sup> = ?",
    A:"a<sup>m:n</sup>",
    B:"a",
    C:"a<sup>m-n</sup>", 
    D:"a<sup>m+n</sup>",
    answer: 3
    },
    {question:"Viết 7<sup>3</sup> . 7<sup>7</sup> dưới dạng một lũy thừa ta được:",
    A:"7<sup>21</sup>",
    B:"7<sup>10</sup>",
    C:"7<sup>4</sup>",
    D:"7<sup>1</sup>",
    answer: 2
    },
    {question:"Chọn câu sai. Cho lũy thừa: 2<sup>5</sup> thì",
    A:"2 là cơ số",
    B:"5 là số mũ",
    C:"2 là số mũ",
    D:"2<sup>5</sup> = 32",
    answer: 3
    },
    {question:"Viết 18<sup>9</sup> : 18<sup>3</sup> dưới dạng một lũy thừa ta được:",
    A:"18<sup>12</sup>",
    B:"18<sup>3</sup>",
    C:"18<sup>6</sup>",
    D:"18<sup>10</sup>",
    answer: 3
    },
    {question:"Số thích hợp điền vào dấu * thỏa mãn: 22 456 + * = 4 567 + 22 456",
    A:"22 456",
    B:"4 567",
    C:"17 889", 
    D:"4 765",
    answer: 2
    },
    {question:"Tìm số tự nhiên x, biết: x - 124 = 567", 
    A:"x = 691",
    B:"x = 443",
    C:"x = 961",
    D:"x = 434",
    answer: 1
    },
    {question:"Tìm số tự nhiên x thoả mãn: x + 5 = 109",
    A:"104",
    B:"114",
    C:"100",
    D:"124",
    answer: 1
    },
    {question:"Tìm số tự nhiên x thỏa mãn: 7 + x = 362",
    A:"300",
    B:"355",
    C:"305",
    D:"362",
    answer: 2
    },
    {question:"Tích 25. 9676 . 4 bằng với",
    A:"1000. 9676",
    B:"9676 + 100",
    C:"9676. 10",
    D:"9676. 100",
    answer: 4
    },
    {question:"Tích 125. 2021. 8 bằng với",
    A:"2021 . 100",
    B:"2021 + 1000",
    C:"1000 . 2021",
    D:"2021 . 10",
    answer: 3
    },
    {question:"Chọn câu đúng:",
    A:"52.53.54 = 510",
    B:"52 . 53 : 54 = 5",
    C:"53 : 5 = 5",
    D:"51 = 1",
    answer: 2
    },    
]
const mediumFloat =[
  {question:"Phép tính x - 4 thực hiện được trong tập số tự nhiên khi:",
    A:"x > 4",
    B:"x ≥ 4",
    C:"x = 3",
    D:"x < 4",
    answer: 2
    },
    {question:"Kết quả của phép tính 117 + 39 + 83 là:",
    A:"339",
    B:"239",
    C:"139",
    D:"439",
    answer: 2
    },
    {question:"Kết quả của phép tính 418 - 18 - 100 là:",
    A:"200",
    B:"300",
    C:"400",
    D:"100",
    answer: 2
    },
    {question:"Hiệu của số 12 300 và 1 200 là:",
    A:"11 100",
    B:"11 111",
    C:"1 100",
    D:"12 100",
    answer: 1
    },
    {question:"23 456 + (34 567 + 56 789) = (? + 34 567) + 56 789. Điền số thích hợp vào dấu ?",
    A:"58 023",
    B:"23 456",
    C:"22 222",
    D:" Đáp án khác",
    answer: 2
    },
    {question:"Cho A = 5 + 5 + 5 + … + 5 (có m số 5). Khẳng định nào sau đây sai?",
    A:"A = 5 × m",
    B:"A = 5 . m",
    C:"A = 20",
    D:"A = 5m",
    answer: 3
    },
    {question:"Phép chia a : b thực hiện được khi:",
    A:"b là số tự nhiên bất kì",
    B:"b = 0",
    C:"b ≠ 0",
    D:"b ≠ 1",
    answer: 3
    },
    {question:"Cho r là số dư trong phép chia a cho b (với b ≠ 0). Khi đó:",
    A:"r = b",
    B:"r > b",
    C:"r > 0",
    D:"0 ≤ r <  b",
    answer: 4
    },
    {question:"Biết (40 + ?). 6 = 40 . 6 + 5. 6. Điền số vào dấu ?",
    A:"5",
    B:"4",
    C:"3",
    D:"6",
    answer: 1
    },
    {question:"Phép nhân có các tính chất nào?",
    A:"Giao hoán",
    B:"Kết hợp",
    C:"Phân phối của phép nhân đối với phép cộng",
    D:"Tất cả đáp án trên",
    answer: 4
    },
    {question:"So sánh hai phép tính a (b + c) và ab + ac",
    A:"a (b + c) = ab + ac",
    B:"a (b + c) ≠ ab + ac",
    C:"a (b + c) ≤ ab + ac",
    D:"a (b + c) > ab + ac",
    answer: 1
    },
    {question:"Hai số tự nhiên a và b (b khác 0), tồn tại số tự nhiên q sao cho a = b.q. Khi đó:",
    A:"a chia hết cho b",
    B:"b chia hết cho a",
    C:"a chia cho b dư r",
    D:"b chia cho a dư r",
    answer: 1
    },
    {question:"Tích a.b bằng:",
    A:"a + a + … + a (a số hạng)",
    B:"a + a + … + a (b số hạng)",
    C:"a.a… a (b thừa số a)",
    D:"a.a…a (a thừa số a)",
    answer: 2
    },
    {question:"Nếu a. b = 0 thì",
    A:"a = 0",
    B:"b = 0",
    C:"a = 0 hoặc b = 0",
    D:"a = b = 0",
    answer: 3
    },
    {question:"64 là lũy thừa của số tự nhiên nào, số mũ bằng bao nhiêu?",
    A:"Lũy thừa của 2, số mũ bằng 8",
    B:"Lũy thừa của 4, số mũ bằng 6",
    C:"Lũy thừa của 8, số mũ bằng 2",
    D:"Lũy thừa của 6, số mũ bằng 4",
    answer: 3
    },
    {question:"So sánh 12<sup>5</sup>: 12<sup>4</sup> và 12",
    A:"12<sup>5</sup>: 12<sup>4</sup> = 12",
    B:"12<sup>5</sup>: 12<sup>4</sup> > 12",
    C:"12<sup>5</sup>: 12<sup>4</sup> < 12",
    D:"12<sup>5</sup>: 12<sup>4</sup> ≠ 12",
    answer: 1
    },
    {question:"So sánh 2 021<sup>6</sup>. 2 021<sup>3</sup> và 2 021<sup>9</sup>",
    A:"2 021<sup>6</sup>. 2 021<sup>3</sup> = 2 021<sup>9</sup>",
    B:"2 021<sup>6</sup>. 2 021<sup>3</sup> ≠ 2 021<sup>9</sup>",
    C:"2 021<sup>6</sup>. 2 021<sup>3</sup> > 2 021<sup>9</sup>",
    D:"2 021<sup>6</sup>. 2 021<sup>3</sup> < 2 021<sup>9</sup>",
    answer: 1
    },
    {question:"Chọn câu sai",
    A:"a<sup>m</sup>. a<sup>n</sup> = a<sup>m+n</sup>",
    B:"a<sup>1</sup> = a",
    C:"a<sup>0</sup> = 0",
    D:"a<sup>m</sup>: a<sup>n</sup> = a<sup>m-n</sup>(a ≠ 0; m ≥ n)",
    answer: 3
    },
    {question:"Tính lũy thừa của 2<sup>6</sup>, ta được:",
    A:"32",
    B:"64",
    C:"16",
    D:"128",
    answer: 2
    },
    {question:"Tính giá trị của lũy thừa 5<sup>4</sup> ta được:",
    A:"20",
    B:"25",
    C:"125",
    D:"625",
    answer: 4
    },
    {question:"Viết 18<sup>10</sup> : 9<sup>0</sup> dưới dạng một lũy thừa ta được:",
    A:"18<sup>10</sup>",
    B:"9<sup>10</sup>",
    C:"3",
    D:"Không có đáp án nào",
    answer: 1
    },
    {question:"Chọn câu đúng.",
    A:"a<sup>m</sup> . a<sup>n</sup> = a<sup>m+n</sup>",
    B:"a . a . a . a . a = 5a",
    C:"a<sup>m</sup> . a<sup>n</sup> = a<sup>m.n</sup>",
    D:"a1 = 1",
    answer: 1
    },
    {question:"Viết gọn tích sau dưới dạng lũy thừa: a.a.a.b.b.b.b.b",
    A:"a<sup>3</sup>.b<sup>4</sup>",
    B:"a<sup>2</sup>. b<sup>3</sup>",
    C:"a<sup>4</sup> . b<sup>3</sup>",
    D:"a<sup>3</sup> . b<sup>5</sup>",
    answer: 4
    },
    {question:"Tìm số tự nhiên x, biết: x + 125 = 145 + 126.", 
    A:"x = 125",
    B:"x = 126",
    C:"x = 271",
    D:"x = 146",
    answer: 4
    },
    {question:"Kết quả của phép tính 781 - 381 + 28 là",
    A:"328",
    B:"428",
    C:"528",
    D:"628",
    answer: 2
    },
    {question:"Kết quả của phép tính: 164 + 117 + 36 - 17",
    A:"269",
    B:"258",
    C:"300",
    D:"400",
    answer: 3
    },
    {question:"Tính nhanh: 463 + 318 + 137 + 22",
    A:"910",
    B:"920",
    C:"930",
    D:"940",
    answer: 4
    },
    {question:"Tính nhanh: 135 + 360 + 65 + 40",
    A:"400",
    B:"500",
    C:"600",
    D:"700",
    answer: 3
    },
    {question:"Tính nhanh tổng 57 + 26 + 34 + 63?",
    A:"200",
    B:"180",
    C:"160",
    D:"100",
    answer: 2
    },
    {question:"Tính nhanh tổng 53 + 25 + 47 + 75?",
    A:"200",
    B:"201",  
    C:"300",   
    D:"100",
    answer: 1
    },
    {question:"Thực hiện phép tính: 15 + 78 + 99 + 42",
    A:"190",
    B:"243",
    C:"234",
    D:"210",
    answer: 3
    },
    {question:"Tính một cách hợp lí: 285 + 470 + 115 + 230",
    A:"400",	
    B:"700",	
    C:"1 100",	
    D:"1 000",
    answer: 3
    },
    {question:"Kết quả của phép tính 547. 63 + 547 . 37 là:",
    A:"54 700",
    B:"5470",
    C:"45 700",
    D:"54 733",
    answer: 1
    },
    {question:"Kết quả của phép tính 159 . 57 - 59 . 57 là:", 
    A:"57",
    B:"157",
    C:"570",
    D:"5 700",
    answer: 4
    },
    {question:"Thực hiện phép tính 129.89 + 129.11",
    A:"12 900",             	
    B:"1 290",      	
    C:"11 610",              	
    D:"12 090",
    answer: 1
    },
    {question:"5269 + 2017 … 2017 + 5962. Dấu thích hợp điền vào chỗ chấm là:",
    A:"<",
    B:">",
    C:"=",
    D:"≠",
    answer: 1
    },
    {question:"Viết gọn tích sau bằng cách dùng lũy thừa: 5. 25. 7. 7",
    A:"7<sup>3</sup>. 5<sup>2</sup>",	
    B:"5<sup>3</sup>. 7<sup>2</sup>",	
    C:"5. 5. 5. 7. 7",	
    D:"5. 5<sup>2</sup>. 7<sup>3</sup>",
    answer: 2
    },
    {question:"Kết quả của phép tính: 24<sup>19</sup>. 24<sup>2</sup>: 24<sup>21</sup>",
    A:"24",                     	
    B:"24",                 	
    C:"24<sup>2</sup>",                   	
    D:"1",
    answer: 4
    },
    {question:"Biết 2<sup>10</sup> = 1 024. Hãy tính 2<sup>9</sup>",
    A:"2 048",	
    B:"512",	
    C:"1 022",	
    D:"Đáp án khác",
    answer: 2
    },
    {question:"Tìm x biết 1 999<sup>6</sup>. 1 999<sup>x</sup> = 1 999<sup>20</sup>",
    A:"x = 14",	
    B:"x = 13",	
    C:"x = 26",	
    D:"x = 0",
    answer: 1
    },
    {question:"So sánh 5<sup>3</sup> và 3<sup>5</sup>",
    A:"5<sup>3</sup> = 3<sup>5</sup>",	
    B:"5<sup>3</sup> > 3<sup>5</sup>",	
    C:"5<sup>3</sup> < 3<sup>5</sup>",	
    D:"5<sup>3</sup> ≥ 3<sup>5</sup>",
    answer: 3
    },
    {question:"Chọn câu sai:",
    A:"5<sup>2</sup> . 5<sup>7</sup> . 5<sup>3</sup> = 5<sup>12</sup>",
    B:"7<sup>12</sup> : 7<sup>8</sup> = 7<sup>4</sup>",
    C:"2021<sup>0</sup> = 0",
    D:"2021<sup>1</sup> = 2021",
    answer: 3
    },
    {question:"Chọn câu đúng.",
    A:"2<sup>3</sup> < 3<sup>2</sup>",
    B:"3<sup>3</sup> > 2<sup>5</sup>",
    C:"2<sup>4</sup> = 2<sup>6</sup>",
    D:"4<sup>3</sup> > 8<sup>2</sup>",
    answer: 1
    },
    {question:"Viết số sau dưới dạng lũy thừa với cơ số cho trước: 125 cơ số 5",
    A:"5<sup>3</sup>",
    B:"3<sup>5</sup>",
    C:"5<sup>125</sup>",
    D:"125<sup>5</sup>",
    answer: 1
    },
    {question:"Chọn kết luận đúng trong các kết luận sau:",
    A:"3<sup>3</sup> . 3<sup>4</sup> = 3<sup>12</sup>",
    B:"3<sup>0</sup> = 0",
    C:"4<sup>2</sup> : 2<sup>3</sup> = 2",
    D:"5<sup>5</sup> : 5 = 1<sup>4</sup>",
    answer: 3
    },
    {question:"Viết kết quả phép tính 12<sup>2</sup> . 2 . 12<sup>5</sup> . 6 dưới dạng một lũy thừa, ta được:",
    A:"12<sup>9</sup>",
    B:"12<sup>8</sup>",
    C:"12<sup>7</sup>",
    D:"12<sup>6</sup>",
    answer: 2
    },
    {question:"Kết quả của phép tính 3<sup>7</sup>.3<sup>2</sup> - 3<sup>9</sup> là:",
    A:"0",
    B:"3",
    C:"3<sup>9</sup>",
    D:"2 . 3<sup>9</sup>",
    answer: 1
    },
    {question:"Viết kết quả phép tính 9<sup>4</sup>.3.9<sup>2</sup>.3 dưới dạng lũy thừa ta được:",
    A:"9<sup>5</sup>",
    B:"9<sup>6</sup>",
    C:"9<sup>7</sup>",
    D:"9<sup>8</sup>",
    answer: 3
    },
    {question:"Tìm số tự nhiên n thỏa mãn 4<sup>n</sup> = 4<sup>3</sup> . 4<sup>5</sup>",
    A:"n = 32",     
    B:"n = 16",     
    C:"n = 8", 
    D:"n = 4",
    answer: 3
    },
    {question:"Số tự nhiên x nào dưới đây thỏa mãn 12<sup>x</sup> = 12<sup>7</sup> : 12<sup>4</sup>",
    A:"x = 6",
    B:"x =  4", 
    C:"x = 11",
    D:"x = 3",
    answer: 4
    },    
]
const hardFloat =[
  {question:"Cho các cách viết sau: A = [a, b, c, d]; B = {2; 13; 45}; C = (1; 2; 3); D = 1. Có bao nhiêu cách viết tập hợp là đúng?",
A:"1",
B:"2",
C:"3",
D:"4",
answer: 1
},
{question:"Cho A = {1; 2; 3; 4} và B = {3; 4; 5}. Tập hợp C gồm các phần tử thuộc tập A nhưng không thuộc tập B là?",
A:"C = {5}",     
B:"C = {1; 2; 5}",     
C:"C = {1; 2}",     
D:"C = {2; 4}",
answer: 3
},
{question:"Cho H là tập hợp các tháng dương lịch có đúng 30 ngày. Phần tử của H là:",
A:"Tháng 1",
B:"Tháng 2",
C:"Tháng 3",
D:"Tháng 4",
answer: 4
},
{question:"Cho A = {Huế, Hà, Nguyệt, Hoài} và B = {Hà, Tuấn, Chi}. Tập hợp C gồm các phần tử thuộc tập A lẫn tập B là?",
A:"C = {Hà}",     
B:"C = {Huế; Chi}",     
C:"C = {Hà; Nguyệt, Chi}",     
D:"C = {Hoài}",
answer: 1
},
{question:"Viết các số tự nhiên có 4 chữ số được lập nên từ chữ số 0 và 1 mà mỗi chữ số xuất hiện hai lần",
A:"1001",		
B:"1010",		
C:"1100",		
D:"1001; 1010; 1100",
answer: 4
},
{question:"Cho C = {x| x là số tự nhiên chia cho 3 dư 1, 3 < x< 18}. Viết tập hợp C.",
A:"C = {6; 9; 12; 15}",
B:"C = (4, 7, 10, 13, 16)",
C:"C = {4; 7; 10; 13; 16}",
D:"C = {4, 10, 13, 16}",
answer: 3
},
{question:"Viết tập hợp P các chữ cái khác nhau trong cụm từ: HOC SINH",
A:"P = {H; O; C; S; I; N; H}",     
B:"P = {H; O; C; S; I; N}",
C:"P = {H; C; S; I; N}",     
D:"P = {H; O; C; H; I; N}",
answer: 2
},
{question:"Viết tập hợp các chữ số của số 9 000.",
A:"{9; 0; 0; 0}",
B:"{0; 9}",
C:"{9}",
D:"{0}",
answer: 2
},
{question:"Viết tập hợp Q gồm các chữ cái khác nhau trong cụm từ: CHUC MUNG",
A:"Q ={C, H, U, M, U, N, G}",
B:"Q ={C, H, U, M, N, G}",
C:"Q ={C, H, U, M, G}",
D:"Q ={C, H, U, C, M, U, N, G}",
answer: 2
},
{question:"Viết B là tập hợp các chữ số xuất hiện trong số 303 530",
A:"B = {3; 0; 3; 5; 3; 0}",
B:"B  ={3; 0; 5; 0}",
C:"B = {3; 0; 3; 5}",
D:"B ={3; 0; 5}",
answer: 4
},
{question:"Cho A = {1; 2; 3; 4; 5} và B = {2; 4; 6; 8}. Các phần tử vừa thuộc tập A vừa thuộc tập B là:",
A:"1; 2",
B:"2; 4",
C:"6; 8",
D:"4; 5",
answer: 2
},
{question:"Hãy viết tập hợp A = {16; 17; 18; 19} dưới dạng chỉ ra tính chất đặc trưng",
A:"A = {x ∈ N|15 < x < 19}",   
B:"A = {x ∈ N|16 < x < 20}", 
C:"A = {x ∈ N|15 < x < 20}",
D:"A = {x ∈ N|15 < x ≤ 20}",
answer: 3
},
{question:"Liệt kê các phần tử của tập hợp A, biết A = { ∈ N | a + b = 5 và a, b ∈ N}",
A:"A = {14; 23; 32; 41}",
B:"A = {12; 23; 32; 41; 50}",
C:"A = {23; 32; 41; 50}",
D:"A = {14; 23; 32; 41; 50}",
answer: 4
},
{question:"Viết tập hợp các chữ cái trong từ HAI PHONG",
A:"M= {H; A; I; P; H; O; N; G}",
B:"M = {H; A; I; P; O; N; G}",
C:"M = {H; A; I}",
D:"M = {P; H; O; N; G}",
answer: 2
},
{question:"Gọi X là tập hợp các chữ cái trong từ “nguyet”. Tìm X",
A:"X = {n; g; u; y; e; t}",
B:"X = {t; e; y; n}",
C:"X = {n; g; u; y; t}",
D:"X = {n; g; u; e; t}",
answer: 1
},
{question:"Tập hợp các tháng dương lịch có đúng 30 ngày là",
A:"P = {1; 3; 5; 7; 8; 10; 12}",
B:"P = {4; 6; 9; 11}",
C:"P = {1; 3; 5; 7}",
D:"P = {1; 3; 4; 6}",
answer: 2
},
{question:"Viết B là tập hợp các chữ số xuất hiện trong số 217 102",
A:"B = {2; 1; 7; 1; 0; 2}",
B:"B = {2; 1; 7; 0}",
C:"B = {2; 0; 2; 1}",
D:"B = {2; 0; 2; 1; 7}",
answer: 2
},
{question:"Viết các số tự nhiên có 4 chữ số được lập nên từ chữ số 0 và 2 mà mỗi chữ số xuất hiện hai lần",
A:"2002",		
B:"2020",		
C:"2200",		
D:"2002; 2020; 2200",
answer: 4
},
{question:"Cho ba số tự nhiên x, y, z (z là số lớn nhất). Trên tia số, điểm x nằm giữa hai điểm y, z. So sánh x, y, z.",
A:"y < x < z",
B:"x < y < z",
C:"x < z < y",
D:"z < x < y",
answer: 1
},
{question:"Dùng ba chữ số 0, 3, 6, viết tất cả các số tự nhiên có ba chữ số mà các chữ số khác nhau.",
A:"360; 306",
B:"360; 306; 603; 630",
C:"603; 630",
D:"360; 603; 630",
answer: 2
},
{question:"Một số tự nhiên được viết bởi ba chữ số 1 và ba chữ số 9 nằm xen kẽ nhau. Tìm số đó.",
A:"191919", 
B:"919191",
C:"119199",
D:"191919 và 919191",
answer: 4
},
{question:"M là tập hợp các số tự nhiên có hai chữ số, chữ số hàng đơn vị lớn hơn chữ số hàng chục là 2. Tìm M.",
A:"M = {79; 68; 57; 46; 35; 24; 13}",
B:"M = {79; 46; 35; 24; 13}",
C:"M = {46; 35; 24; 13}",
D:"M = {69; 58; 47; 36; 25; 14}",
answer: 1
},
{question:"Nếu 1179 < 11x9< 1199 thì chữ số x là:",
A:"x = 3",
B:"x = 27",
C:"x = 8",
D:"x = 0",
answer: 3
},
{question:"Chữ số x là bao nhiêu để  x9x9< 1920?",
A:"0",
B:"1",
C:"2",
D:"3",
answer: 2
},
{question:"Cho tập hợp B gồm 100 số tự nhiên đầu tiên. Khẳng định nào sau đây đúng?",
A:"0 ∉ B",
B:"B = {x ∈ N | x ≤ 100}",
C:"B = { x ∈ N | x < 100}",
D:"100 ∈ B",
answer: 3
},
{question:"Cho ba chữ số 1, 2, 4. Hỏi có bao nhiêu số tự nhiên có 3 chữ số mà các chữ số khác nhau?",
A:"4",		
B:"6",			
C:"5",			
D:"3",
answer: 2
},
{question:"Cho các chữ số là 3; 1; 8; 0 thì số tự nhiên nhỏ nhất có bốn chữ số khác nhau được tạo thành là:",
A:"1038",
B:"1083",
C:"1308",
D:"1380",
answer: 1 
},
{question:"Thêm chữ số 5 vào đằng trước số tự nhiên có 2 chữ số thì ta được số tự nhiên mới.",
A:"Hơn số tự nhiên cũ 5 đơn vị",
B:"Hơn số tự nhiên cũ 50 đơn vị", 
C:"Hơn số tự nhiên cũ 500 đơn vị",
D:"Hơn số tự nhiên cũ 5000 đơn vị",
answer: 3
},
{question:"Điền chữ số thích hợp vào dấu * trong phép toán: 1357 < 13*7 < 1387",
A:"6",			
B:"7",			
C:"8",			
D:"6 hoặc 7",
answer: 4
},
{question:"Số tự nhiên lớn nhất và số tự nhiên nhỏ nhất có bốn chữ số khác nhau là:",
A:"9 999 và 1 000",
B:"9 876 và 1 023",
C:"9 876 và 0 123",
D:"6 789 và 4 321",
answer: 2
},
{question:"Cho các chữ số 0; 2; 3; 5. Số tự nhiên nhỏ nhất có bốn chữ số khác nhau lập được từ các chữ số này là:",
A:"0 235",
B:"3 250",
C:"2 035",
D:"5 320",
answer: 3
},
{question:"Thêm chữ số 7 vào đằng trước một số tự nhiên có ba chữ số thì ta được số mới:",
A:"Hơn số tự nhiên cũ 700 đơn vị.",
B:"Kém số tự nhiên cũ 700 đơn vị.",
C:"Hơn số tự nhiên cũ 7 000 đơn vị.",
D:"Kém số tự nhiên cũ 7 000 đơn vị.",
answer: 3
},
{question:"Viết tập hợp N các số tự nhiên chẵn x thỏa mãn: 317 ≤ x ≤ 322.",
A:"N = {318; 320; 322}",
B:"N = {317; 318; 319; 320; 321; 322}",
C:"N = {318; 320}",
D:"N = {317; 318; 320}",
answer: 1
},
{question:"Liệt kê các phần tử của tập hợp E = { x| x là số tự nhiên, x : 15 = 0}",
A:"E = {0}",
B:"Tập E rỗng",
C:"E có vô số phần tử",
D:"E = {15}",
answer: 1
},
{question:"Viết tập hợp các số tự nhiên có ba chữ số khác nhau từ các số 1; 2; 7 là",
A:"Q = {127; 172}",
B:"Q = {127; 172; 217; 271}",
C:"Q = {127; 172; 217; 271; 712; 721}",
D:"Q = {712; 721}",
answer: 3
},
{question:"Có bao nhiêu số tự nhiên nhỏ hơn số 1 999?",
A:"2001",
B:"1998",
C:"1999", 
D:"2000",
answer: 3
},
{question:"Cho tập hợp A = {0; 2; 4; 6; 8}. Có bao nhiêu phần tử của tập hợp A thuộc tập N*?",
A:"2",
B:"3",
C:"4",
D:"5",
answer: 3
},
{question:"Tập hợp các số tự nhiên không vượt quá 5 gồm bao nhiêu phần tử?",
A:"4 phần tử",
B:"5 phần tử",
C:"6 phần tử",
D:"7 phần tử",
answer: 3
},
{question:"Điền số vào dấu “…” để được các số tăng dần hơn kém nhau 3 đơn vị: 35,…,…",
A:"36, 37",
B:"38, 41",
C:"37, 40",
D:"32, 29",
answer: 2
},
{question:"Q là tập hợp các nước tham gia khối ASEAN. Chọn đáp án đúng",
A:"Việt Nam không thuộc Q",
B:"Singapore thuộc Q",
C:"Lào không thuộc Q",
D:"Nga thuộc Q",
answer: 2
},
{question:"Cho a > 6, b < 3, so sánh a và b",
A:"a < b",
B:"a = b",
C:"a ≤ b",
D:"a > b",
answer: 4
},
{question:"Cho M={1;2;3}. Trong các tập hợp sau tập hợp nào là tập hợp con của M.",
A:"A={0;1}",	                  
B:"B={0;2}",		     
C:"C={3;4}",	             
D:"D={1;3}",
answer: 4
},
{question:"Trong tập hợp số tự nhiên phép tính 10 - x không thực hiện được khi nào?",
A:"x > 10",
B:"x = 10",
C:"x ≤ 10",
D:"x < 10",
answer: 1
},
{question:"Tìm số nhỏ nhất trong các số sau:",
A:"2918",			
B:"2981",		
C:"2819",		
D:"2891",
answer: 3
},
{question:"Tổng các số tự nhiên x thỏa mãn 5≤x≤10  là:",
A:"45",
B:"15",
C:"30",
D:"50",
answer: 1
},
{question:"E gồm các số tự nhiên có hai chữ số mà chữ số tận cùng là 5. Số phần tử của tập hợp E là",
A:"10 phần tử",
B:"9 phần tử",
C:"8 phần tử",
D:"5 phần tử",
answer: 2
},
{question:"Tập hợp T gồm các tháng của Quý II. Tìm T",
A:"{tháng 1; tháng 2; tháng 3}",
B:"{tháng 4; tháng 5}",
C:"{tháng 4; tháng 5; tháng 6}",
D:"{tháng 7; tháng 8}", 
answer: 3
},
{question:"Tập hợp M gồm các số tự nhiên có hai chữ số, các chữ số giống nhau. M có bao nhiêu phần tử?",
A:"2 phần tử",
B:"10 phần tử",
C:"11 phần tử",
D:"9 phần tử",
answer: 4
},
{question:"Cho tập hợp B = {m; n; p; q}. Số tập hợp con có 2 phần tử của tập hợp B là",
A:"6",
B:"4",
C:"5",
D:"3",
answer: 1
},
{question:"Số phần tử của tập hợp P gồm các chữ cái trong cụm từ “SEA GAMES” là",
A:"7",
B:"8",
C:"5",
D:"6",
answer: 3
},
{question:"Dạng tổng quát của số tự nhiên chia cho 7 dư 5 là đáp án nào sau đây?",
A:"5k + 7 (k ∈ N)",
B:"7k + 2 (k ∈ N)", 
C:"7k + 5 (k ∈ N)",
D:"7k + 1 (k ∈ N)",
answer: 3
},
{question:"Tích 10.10.10.100  được viết dưới dạng lũy thừa gọn nhất là:",
A:"10<sup>5</sup>",
B:"10<sup>4</sup>",
C:"100<sup>2</sup>",
D:"20<sup>5</sup>",
answer: 1
},
{question:"Viết số abcdưới dạng lũy thừa của 10:",
A:"a.10<sup>2</sup> + b.10<sup>1</sup> + c.10<sup>2</sup>",
B:"a.10<sup>1</sup> + b.10<sup>2</sup> + c.10<sup>0</sup>",
C:"a.10<sup>2</sup> + b.10<sup>1</sup> + c.10<sup>0</sup>",
D:"a.10<sup>2</sup>  + b.10<sup>0</sup> + c.10<sup>1</sup>",
answer: 3
},
{question:"Viết số 81 dưới dạng lũy thừa. Chọn câu sai.",
A:"3<sup>4</sup>",
B:"9<sup>2</sup>",
C:"81<sup>1</sup>",
D:"2<sup>9</sup>",
answer: 4
},
{question:"Tìm số tự nhiên x biết rằng nếu cộng thêm 31 đơn vị ta thu được một số tự nhiên là 55",
A:"x = 24",	
B:"x = 25",	
C:"x = 26",	
D:"x = 27",
answer: 1
},
{question:"Tìm số tự nhiên x, biết nếu lấy 25 cộng với x thì ta được một số có giá trị gấp 5 lần số 12.",
A:"x = 30",	
B:"x = 35",	
C:"x = 40",	
D:"x = 45",
answer: 2
},
{question:"Tính tổng của số tự nhiên lớn nhất có bốn chữ số khác nhau và số tự nhiên nhỏ nhất có ba chữ số khác nhau.",
A:"8 888",	
B:"8 899",	
C:"9 999",	
D:"9 978",
answer: 4
},
{question:"Tính nhanh 125. 1975. 4. 8. 25",
A:"1 975 000 000",
B:"1 975 000",
C:"19 750 000",
D:"197 500 000",
answer: 4
},
{question:"Tìm số tự nhiên x, biết: (x - 5).1000 = 0.",
A:"x = 5",
B:"x = 1000",
C:"x = 7", 
D:"x = 5000",
answer: 1
},
{question:"Số tự nhiên x nào dưới đây thỏa mãn: 2021.(x - 2021) = 2021.",
A:"2 020",
B:"2 021",
C:"2 022",
D:"2 023",
answer: 3
},
{question:"Kết quả của phép tính 12.100 + 100.36 - 100.19 là:",
A:"29 000",     
B:"3 800",     
C:"290",     
D:"2 900",
answer: 4
},
{question:"Thực hiện phép tính (56 . 35 + 56 . 18) : 53 ta được kết quả là:",
A:"12",     
B:"28",     
C:"53",     
D:"56",
answer: 4
},
{question:"Kết quả phép tính 5 - 5 : 5 + 5 là:",
A:"9",
B:"5",
C:"0",
D:"Kết quả khác",
answer: 1
},
{question:"Kết quả của phép tính 13.52 + 52.36 - 52.19 là",
A:"1 650",	
B:"2 548",	
C:"884",	
D:"1 560",
answer: 4
},
{question:"Tìm x thỏa mãn: (145.x - 435). (x - 57) = 0",
A:"x = 57",	
B:"x = 3", 	
C:"Đáp án A và B",	
D:"Không xác định được",
answer: 3
},
{question:"Tìm số tự nhiên x biết: 40. (70 - x) = 40",
A:"x = 70",	
B:"x = 71",	
C:"x = 61",	
D:"x = 69",
answer: 4
},
{question:"Kết quả của phép nhân 25.15.4.6 là",
A:"9 000",	
B:"3 750",	
C:"6 000",	
D:"6 900",	
answer: 1
},
{question:"Viết gọn tích sau bằng cách dùng lũy thừa: 1000. 10000. 100000",
A:"10<sup>3</sup>. 10<sup>4</sup>. 10<sup>5</sup>",	
B:"1 000. 10<sup>9</sup>",	
C:"10<sup>3+4+5</sup>",	
D:"10<sup>12</sup>",
answer: 4
},
{question:"Viết kết quả phép tính sau dưới dạng lũy thừa: 3<sup>3</sup>. 18 - 3<sup>3</sup>. 15",		
A:"3<sup>4</sup>",	
B:"3. 3<sup>3</sup>",	
C:"81",	
D:"9. 9",
answer: 1
},
{question:"Viết kết quả phép tính sau dưới dạng lũy thừa: 3<sup>6</sup>. 3<sup>2</sup> + 2. 81<sup>2</sup>",
A:"3. 3<sup>8</sup>",	
B:"3<sup>9</sup>",	
C:"3<sup>8</sup> + 2. 3<sup>8</sup>",	
D:"9<sup>3</sup>",
answer: 2
},
{question:"Viết tổng sau dưới dạng bình phương của một số tự nhiên: 1 + 3 + 5 +7.",
A:"42",                 	
B:"162",          	
C:"22",                  	
D:"82",
answer: 1
},
{question:"Viết số 603 thành tổng giá trị các chữ số của nó bằng cách dùng các lũy thừa của 10.",
A:"603 = 6. 100 + 3. 10",
B:"603 = 6.10<sup>2</sup> + 10 + 3",
C:"603 = 6.10<sup>2</sup> + 3",
D:"603 = 6 + 0 + 3",
answer: 3
},
{question:"Tìm n biết: 4<sup>3</sup> + n = 3n",
A:"n = 64",	
B:"n = 3",	
C:"n = 8",	
D:"n = 32",
answer: 4
},
{question:"Tìm n biết: 5<sup>n</sup> < 90",
A:"n = 0",	
B:"n = 1",	
C:"n = 2",	
D:"Tất cả đáp án trên",
answer: 4
},
{question:"Có bao nhiêu số tự nhiên n thỏa mãn 14 < 6<sup>n</sup> < 50",
A:"Không tồn tại n",	
B:"1 số",	
C:"2 số",	
C:"3 số",
answer: 2
},
{question:"Tính 24  + 16 ta được kết quả dưới dạng lũy thừa là:",
A:"2<sup>20</sup>",
B:"2<sup>4</sup>",
C:"2<sup>5</sup>",
D:"2<sup>10</sup>",
answer: 3
},
{question:"Tìm số tự nhiên n biết 3<sup>n</sup> = 81",
A:"n = 2", 
B:"n = 4",
C:"n = 5",
D:"n = 8",
answer: 2
},
{question:"Viết cấu tạo số 2 021 dưới dạng tổng các lũy thừa của 10 là:",
A:"2021 = 2. 10<sup>4</sup> + 2. 10<sup>2</sup> + 10<sup>4</sup>",
B:"2021 = 2. 10<sup>3</sup> + 2 . 10 + 10<sup>0</sup>",
C:"2021 = 2. 10<sup>4</sup> + 2 . 10<sup>2</sup> + 10",
D:"2021 = 2.10<sup>3</sup> + 2. 10<sup>2</sup> + 10<sup>0</sup>",
answer: 2
},
{question:"Viết kết quả phép tính 6<sup>3</sup> . 2 . 6<sup>4</sup> . 3 dưới dạng một lũy thừa ta được:",
A:"6<sup>6</sup>",
B:"6<sup>7</sup>",
C:"6<sup>8</sup>",
D:"6<sup>9</sup>",
answer: 3
},
{question:"Số tự nhiên được biểu diễn bởi 2 . 10<sup>3</sup> + 7 . 10<sup>2</sup> + 8 . 10 + 7 . 10<sup>0</sup>  là:",
A:"2 787",
B:"2 7870",
C:"278",
D:"2 780",
answer: 1
},
{question:"Số tự nhiên n thỏa mãn 2<sup>n</sup> = 4<sup>2</sup> là:",
A:"n = 3",
B:"n = 4",
C:"n = 5",
D:"n = 6",
answer: 2
},
{question:"Số tự nhiên n thỏa mãn 3<sup>2n+1</sup> = 27 là:",
A:"0",
B:"3",
C:"2",
D:"1", 
answer: 4
},
{question:"Viết thương sau dưới dạng một lũy thừa: 64<sup>4</sup>.16<sup>4</sup> : 420",
A:"4<sup>5</sup>",
B:"4<sup>4</sup>", 
C:"4<sup>3</sup>", 
D:"4<sup>2</sup>",
answer: 4
},
{question:"Đưa 25. 10 . 4 thành lũy thừa cơ số 10:",
A:"10<sup>2</sup>", 
B:"10<sup>3</sup>",
C:"10<sup>4</sup>",
D:"10",
answer: 3
},
{question:"Tìm số tự nhiên a biết: (a - 2)<sup>3</sup> = 27",
A:"1",
B:"5",
C:"6",
D:"9",
answer: 2
},
{question:"Tìm số tự nhiên m thỏa mãn 20<sup>2018</sup> < 20<sup>m</sup> < 20<sup>2020</sup> ?",
A:"m = 2 020",     
B:"m = 2 019",     
C:"m = 2 018",     
D:"m = 20", 
answer: 2
},
{question:"Tìm số tự nhiên x biết: 100 - (7 + x)<sup>2</sup> =  19",
A:"x = 3",
B:"x = 12",
C:"x = 1",
D:"x = 2",
answer: 4
},
{question:"Tìm số tự nhiên x biết: (x : 12)<sup>3</sup> =3<sup>11</sup> : 3<sup>8</sup>",
A:"x = 21",
B:"x = 12",
C:"x =  9",
D:"x = 36",
answer: 4
},
{question:"Số tự nhiên n thỏa mãn 2<sup>n</sup> = 128 là:",
A:"n =  4",
B:"n = 5",
C:"n = 6",
D:"n =  7",
answer: "4",
},
{question:"Chọn đáp án đúng?",
A:"5<sup>2</sup> . 5<sup>3</sup> . 5<sup>4</sup> = 5<sup>10</sup>",
B:"5<sup>2</sup> . 5<sup>3</sup> . 25 = 5<sup>7</sup>",
C:"5<sup>3</sup> . 5 = 25<sup>3</sup>",
D:"5<sup>1</sup> = 1",
answer: 2
},
{question:"Tìm số tự nhiên x biết (x - 47) - 115 = 0",
A:"x = 32",
B:"x = 162",
C:"x = 111",
D:"x = 64",
answer: 2
},
{question:"Tìm số tự nhiên a biết: (215 - x) + 100 = 164",
A:"279",
B:"212",
C:"151",
D:"175",
answer: 3
},
{question:"Số tự nhiên x thỏa mãn 124 + (118 - x) = 125 là:",
A:"x = 1",
B:"x = 367",
C:"x = 117",
D:"x = 119",
answer: 3
},
{question:"Tìm số tự nhiên x, biết rằng nếu nhân nó với 7 rồi cộng thêm 51, sau đó chia cho 3 thì được 24.",
A:"x = 1",	
B:"x = 2",	
C:"x = 3",	
D:"x = 0",
answer: 3
},
{question:"Giá trị của x thỏa mãn 65 - 4<sup>x+2</sup> = 20200",
A:"2",
B:"4",
C:"3",
D:"1",
answer: 4 
},
{question:"Tìm số tự nhiên x, biết: 10 + 2x = 4<sup>5</sup> : 4<sup>3</sup>", 
A:"3",
B:"2",
C:"1",
D:"4",
answer: 1
},
{question:"Số tự nhiên x cho bởi: 5.(x + 15) = 5<sup>3</sup>. Giá trị của x là:",
A:"9",
B:"10", 
C:"11",
D:"12",
answer: 2
},
{question:"Tính tổng 215 + 217 + 219 + 221 + 223 được kết quả là:", 
A:"1 095",
B:"995", 
C:"1 000", 
D:"1 085",
answer: 1
},
{question:"Hãy tìm số tự nhiên x biết: (x - 35) - 120 = 0",
A:"x = 125",
B:"x = 135",
C:"x = 145",
D:"x = 155",
answer: 4
},
{question:"Bạn Nam có 127 viên bi, bạn Tuấn cho bạn Nam thêm 17 viên bi nữa. Hỏi bạn Nam có tất cả bao nhiêu viên bi?",
A:"134 viên bi",
B:"144 viên bi",
C:"124 viên bi",
D:"149 viên bi",
answer: 2
},
]

const allData =easyInt.concat(easyFloat,mediumInt,mediumFloat,hardFloat,hardInt)
